import { useCallback, useEffect, useMemo, useState } from 'react';
import { BookOpenCheck, Edit3, KeyRound, Plus, RefreshCw, ShieldCheck, Trash2, UserCog, UsersRound } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import type { RoleDefinition, RoleInput, TreatmentCatalogItem, UserAccount, UserAccountInput } from '../../shared/types';
import { useApp } from '../context/AppContext';
import { Badge, Button, Card, DateText, EmptyState, FormField, IconButton, LoadingState, Modal, Money } from './UI';

interface Permission {code:string;name:string;description:string}
const emptyUser:UserAccountInput={username:'',displayName:'',password:'',language:'en',status:'active',roleIds:[]};

export function UserAdministration(){
  const {t}=useTranslation();const{session,run,notify}=useApp();const[users,setUsers]=useState<UserAccount[]>([]);const[roles,setRoles]=useState<RoleDefinition[]>([]);const[permissions,setPermissions]=useState<Permission[]>([]);const[loading,setLoading]=useState(true);const[userEditor,setUserEditor]=useState<UserAccount|null|undefined>(undefined);const[roleEditor,setRoleEditor]=useState<RoleDefinition|null|undefined>(undefined);const[resetTarget,setResetTarget]=useState<UserAccount|null>(null);const[deleteTarget,setDeleteTarget]=useState<RoleDefinition|null>(null);
  const load=useCallback(async()=>{if(!session)return;setLoading(true);try{const[data,access]=await Promise.all([run(()=>window.dentiva.users.list(session.token)),run(()=>window.dentiva.users.roles(session.token))]);setUsers(data);setRoles(access.roles);setPermissions(access.permissions);}catch{}finally{setLoading(false);}},[session,run]);useEffect(()=>{void load();},[load]);
  if(loading)return<LoadingState/>;
  const removeRole=async()=>{if(!session||!deleteTarget)return;try{await run(()=>window.dentiva.users.deleteRole(session.token,deleteTarget.id));notify('success',t('common.success'));setDeleteTarget(null);await load();}catch{}};
  return<div className="administration-stack"><Card title={t('admin.users')}action={<div className="card-actions"><IconButton label={t('common.refresh')}icon={RefreshCw}onClick={load}/><Button size="sm"icon={Plus}onClick={()=>setUserEditor(null)}>{t('admin.addUser')}</Button></div>}>{users.length===0?<EmptyState icon={UsersRound}title={t('admin.noUsers')}body={t('admin.noUsersBody')}/>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>{t('admin.account')}</th><th>{t('admin.roles')}</th><th>{t('common.language')}</th><th>{t('admin.lastLogin')}</th><th>{t('common.status')}</th><th>{t('common.actions')}</th></tr></thead><tbody>{users.map((user)=><tr key={user.id}><td><b>{user.displayName}</b><small className="table-sub">@{user.username}{user.id===session?.user.id?` · ${t('admin.currentAccount')}`:''}</small></td><td><div className="inline-badges">{user.roles.map((role)=><Badge key={role.id}tone="blue">{role.name}</Badge>)}</div></td><td>{user.language==='bn'?t('common.bengali'):t('common.english')}</td><td>{user.lastLoginAt?<DateText value={user.lastLoginAt}withTime/>:'—'}</td><td><Badge tone={user.status==='active'?'green':user.status==='locked'?'amber':'red'}>{t(`admin.${user.status}`)}</Badge></td><td><div className="row-actions"><IconButton label={t('common.edit')}icon={Edit3}onClick={()=>setUserEditor(user)}/><IconButton label={t('admin.resetPassword')}icon={KeyRound}onClick={()=>setResetTarget(user)}/></div></td></tr>)}</tbody></table></div>}</Card>
    <Card title={t('admin.roles')}action={<Button size="sm"icon={Plus}onClick={()=>setRoleEditor(null)}>{t('admin.addRole')}</Button>}><p className="card-intro">{t('admin.rolesHelp')}</p><div className="role-grid">{roles.map((role)=><article key={role.id}><header><span className="role-icon"><ShieldCheck/></span><div><h3>{role.name}</h3><p>{role.description||t('admin.customRole')}</p></div>{role.isSystem&&<Badge tone="neutral">{t('admin.protected')}</Badge>}</header><div className="role-meta"><span>{t('admin.userCount',{count:role.userCount})}</span><span>{t('admin.permissionCount',{count:role.permissions.length})}</span></div>{!role.isSystem&&<footer><Button size="sm"variant="quiet"icon={Edit3}onClick={()=>setRoleEditor(role)}>{t('common.edit')}</Button><IconButton label={t('common.delete')}icon={Trash2}onClick={()=>setDeleteTarget(role)}/></footer>}</article>)}</div></Card>
    <UserEditor open={userEditor!==undefined}user={userEditor??null}roles={roles}onClose={()=>setUserEditor(undefined)}onSaved={async()=>{setUserEditor(undefined);await load();}}/>
    <RoleEditor open={roleEditor!==undefined}role={roleEditor??null}permissions={permissions}onClose={()=>setRoleEditor(undefined)}onSaved={async()=>{setRoleEditor(undefined);await load();}}/>
    <PasswordReset user={resetTarget}onClose={()=>setResetTarget(null)}/>
    <Modal open={Boolean(deleteTarget)}onClose={()=>setDeleteTarget(null)}title={t('admin.deleteRole')}subtitle={deleteTarget?.name}size="sm"danger footer={<><Button variant="secondary"onClick={()=>setDeleteTarget(null)}>{t('common.cancel')}</Button><Button variant="danger"onClick={removeRole}>{t('common.delete')}</Button></>}><p>{t('admin.deleteRoleBody')}</p></Modal>
  </div>;
}

function UserEditor({open,user,roles,onClose,onSaved}:{open:boolean;user:UserAccount|null;roles:RoleDefinition[];onClose:()=>void;onSaved:()=>void}){
  const{t}=useTranslation();const{session,run}=useApp();const[form,setForm]=useState<UserAccountInput>(emptyUser);const[busy,setBusy]=useState(false);useEffect(()=>{if(!open)return;setForm(user?{username:user.username,displayName:user.displayName,language:user.language,status:user.status==='disabled'?'disabled':'active',roleIds:user.roles.map((role)=>role.id)}:{...emptyUser,roleIds:[]});},[open,user]);const toggleRole=(id:string)=>setForm((value)=>({...value,roleIds:value.roleIds.includes(id)?value.roleIds.filter((role)=>role!==id):[...value.roleIds,id]}));const save=async()=>{if(!session)return;setBusy(true);try{if(user)await run(()=>window.dentiva.users.update(session.token,user.id,{username:form.username,displayName:form.displayName,language:form.language,status:form.status,roleIds:form.roleIds}));else await run(()=>window.dentiva.users.create(session.token,form));onSaved();}catch{}finally{setBusy(false);}};
  return<Modal open={open}onClose={onClose}title={user?t('admin.editUser'):t('admin.addUser')}subtitle={t('admin.userHelp')}size="lg"footer={<><Button variant="secondary"onClick={onClose}>{t('common.cancel')}</Button><Button icon={UserCog}onClick={save}disabled={busy||form.displayName.trim().length<2||form.username.trim().length<2||form.roleIds.length===0||(!user&&(form.password?.length??0)<10)}>{busy?t('common.saving'):t('common.save')}</Button></>}><div className="form-grid cols-2"><FormField label={t('common.name')}required><input value={form.displayName}onChange={(event)=>setForm({...form,displayName:event.target.value})}/></FormField><FormField label={t('admin.username')}required><input value={form.username}onChange={(event)=>setForm({...form,username:event.target.value})}autoCapitalize="none"spellCheck={false}/></FormField>{!user&&<FormField label={t('admin.temporaryPassword')}required className="span-2"hint={t('setup.passwordHint')}><input type="password"value={form.password??''}onChange={(event)=>setForm({...form,password:event.target.value})}autoComplete="new-password"/></FormField>}<FormField label={t('common.language')}><select value={form.language}onChange={(event)=>setForm({...form,language:event.target.value==='bn'?'bn':'en'})}><option value="en">{t('common.english')}</option><option value="bn">{t('common.bengali')}</option></select></FormField><FormField label={t('common.status')}><select value={form.status}onChange={(event)=>setForm({...form,status:event.target.value==='disabled'?'disabled':'active'})}><option value="active">{t('admin.active')}</option><option value="disabled">{t('admin.disabled')}</option></select></FormField><div className="span-2"><span className="field-label">{t('admin.roles')} *</span><div className="choice-grid">{roles.map((role)=><label key={role.id}className={form.roleIds.includes(role.id)?'selected':''}><input type="checkbox"checked={form.roleIds.includes(role.id)}onChange={()=>toggleRole(role.id)}/><span><b>{role.name}</b><small>{role.description}</small></span></label>)}</div></div></div></Modal>;
}

function RoleEditor({open,role,permissions,onClose,onSaved}:{open:boolean;role:RoleDefinition|null;permissions:Permission[];onClose:()=>void;onSaved:()=>void}){
  const{t}=useTranslation();const{session,run}=useApp();const[form,setForm]=useState<RoleInput>({name:'',description:'',permissions:[]});const[busy,setBusy]=useState(false);useEffect(()=>{if(open)setForm(role?{name:role.name,description:role.description,permissions:role.permissions}:{name:'',description:'',permissions:[]});},[open,role]);const groups=useMemo(()=>Object.entries(permissions.reduce<Record<string,Permission[]>>((result,item)=>{const group=item.code.split('.')[0]??'other';(result[group]??=[]).push(item);return result;},{})),[permissions]);const toggle=(code:string)=>setForm((value)=>({...value,permissions:value.permissions.includes(code)?value.permissions.filter((item)=>item!==code):[...value.permissions,code]}));const save=async()=>{if(!session)return;setBusy(true);try{if(role)await run(()=>window.dentiva.users.updateRole(session.token,role.id,form));else await run(()=>window.dentiva.users.createRole(session.token,form));onSaved();}catch{}finally{setBusy(false);}};
  return<Modal open={open}onClose={onClose}title={role?t('admin.editRole'):t('admin.addRole')}subtitle={t('admin.permissionHelp')}size="xl"footer={<><Button variant="secondary"onClick={onClose}>{t('common.cancel')}</Button><Button icon={ShieldCheck}onClick={save}disabled={busy||form.name.trim().length<2}>{busy?t('common.saving'):t('common.save')}</Button></>}><div className="form-grid cols-2"><FormField label={t('admin.roleName')}required><input value={form.name}onChange={(event)=>setForm({...form,name:event.target.value})}/></FormField><FormField label={t('admin.description')}><input value={form.description??''}onChange={(event)=>setForm({...form,description:event.target.value})}/></FormField></div><div className="permission-groups">{groups.map(([group,items])=><section key={group}><header><b>{group.replaceAll('_',' ')}</b><Button size="sm"variant="quiet"onClick={()=>setForm((value)=>({...value,permissions:[...new Set([...value.permissions,...(items??[]).map((item)=>item.code)])]}))}>{t('admin.selectGroup')}</Button></header>{(items??[]).map((permission)=><label key={permission.code}className={form.permissions.includes(permission.code)?'selected':''}><input type="checkbox"checked={form.permissions.includes(permission.code)}onChange={()=>toggle(permission.code)}/><span><b>{permission.name}</b><small>{permission.description}</small></span></label>)}</section>)}</div></Modal>;
}

function PasswordReset({user,onClose}:{user:UserAccount|null;onClose:()=>void}){const{t}=useTranslation();const{session,run,notify}=useApp();const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);useEffect(()=>{setPassword('');setConfirm('');},[user]);const save=async()=>{if(!session||!user||password!==confirm)return;setBusy(true);try{await run(()=>window.dentiva.users.resetPassword(session.token,user.id,password));notify('success',t('admin.passwordResetDone'));onClose();}catch{}finally{setBusy(false);}};return<Modal open={Boolean(user)}onClose={onClose}title={t('admin.resetPassword')}subtitle={user?.displayName}size="sm"footer={<><Button variant="secondary"onClick={onClose}>{t('common.cancel')}</Button><Button icon={KeyRound}onClick={save}disabled={busy||password.length<10||password!==confirm}>{t('common.save')}</Button></>}><div className="form-grid"><FormField label={t('settings.newPassword')}required hint={t('setup.passwordHint')}><input type="password"value={password}onChange={(event)=>setPassword(event.target.value)}autoComplete="new-password"/></FormField><FormField label={t('setup.confirmPassword')}required><input type="password"value={confirm}onChange={(event)=>setConfirm(event.target.value)}autoComplete="new-password"/></FormField></div></Modal>}

const emptyTreatment={code:'',name:'',category:'',defaultFeeMinor:0,durationMinutes:30,description:'',taxRate:0,active:true};
export function TreatmentCatalog(){const{t}=useTranslation();const{session,run,notify,bootstrap}=useApp();const[items,setItems]=useState<TreatmentCatalogItem[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const[editor,setEditor]=useState<TreatmentCatalogItem|null|undefined>(undefined);const load=useCallback(async()=>{if(!session)return;setLoading(true);try{const data=await run(()=>window.dentiva.records.list(session.token,{entity:'treatments',page:1,pageSize:100,search}));setItems(data.items as unknown as TreatmentCatalogItem[]);}catch{}finally{setLoading(false);}},[session,run,search]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),search?250:0);return()=>window.clearTimeout(timer);},[load,search]);return<div className="administration-stack"><Card title={t('catalog.title')}action={<Button size="sm"icon={Plus}onClick={()=>setEditor(null)}>{t('catalog.add')}</Button>}><p className="card-intro">{t('catalog.help')}</p><div className="table-toolbar"><div className="search-box"><BookOpenCheck/><input value={search}onChange={(event)=>setSearch(event.target.value)}placeholder={t('catalog.search')}/></div><IconButton label={t('common.refresh')}icon={RefreshCw}onClick={load}/></div>{loading?<LoadingState/>:items.length===0?<EmptyState icon={BookOpenCheck}title={t('catalog.empty')}body={t('catalog.emptyBody')}action={<Button icon={Plus}onClick={()=>setEditor(null)}>{t('catalog.add')}</Button>}/>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>{t('catalog.code')}</th><th>{t('catalog.service')}</th><th>{t('catalog.category')}</th><th className="num">{t('catalog.fee')}</th><th>{t('catalog.duration')}</th><th>{t('catalog.tax')}</th><th>{t('common.status')}</th><th>{t('common.actions')}</th></tr></thead><tbody>{items.map((item)=><tr key={item.id}><td className="code-cell">{item.code}</td><td><b>{item.name}</b><small className="table-sub">{item.description||'—'}</small></td><td>{item.category||'—'}</td><td className="num"><Money minor={item.defaultFeeMinor}symbol={bootstrap?.clinic?.currencySymbol}/></td><td>{item.durationMinutes?`${item.durationMinutes} ${t('settings.minutes')}`:'—'}</td><td>{item.taxRate}%</td><td><Badge tone={item.active?'green':'neutral'}>{item.active?t('common.active'):t('common.inactive')}</Badge></td><td><IconButton label={t('common.edit')}icon={Edit3}onClick={()=>setEditor(item)}/></td></tr>)}</tbody></table></div>}</Card><TreatmentEditor open={editor!==undefined}item={editor??null}onClose={()=>setEditor(undefined)}onSaved={async()=>{setEditor(undefined);notify('success',t('common.success'));await load();}}/></div>}

function TreatmentEditor({open,item,onClose,onSaved}:{open:boolean;item:TreatmentCatalogItem|null;onClose:()=>void;onSaved:()=>void}){const{t}=useTranslation();const{session,run}=useApp();const[form,setForm]=useState(emptyTreatment);const[busy,setBusy]=useState(false);useEffect(()=>{if(open)setForm(item?{code:item.code,name:item.name,category:item.category??'',defaultFeeMinor:item.defaultFeeMinor,durationMinutes:item.durationMinutes??30,description:item.description??'',taxRate:item.taxRate,active:item.active}:{...emptyTreatment});},[open,item]);const save=async()=>{if(!session)return;setBusy(true);try{const input={...form,category:form.category||null,description:form.description||null};if(item)await run(()=>window.dentiva.records.update(session.token,'treatments',item.id,input));else await run(()=>window.dentiva.records.create(session.token,'treatments',input));onSaved();}catch{}finally{setBusy(false);}};return<Modal open={open}onClose={onClose}title={item?t('catalog.edit'):t('catalog.add')}subtitle={t('catalog.editorHelp')}size="lg"footer={<><Button variant="secondary"onClick={onClose}>{t('common.cancel')}</Button><Button icon={BookOpenCheck}onClick={save}disabled={busy||form.code.trim().length===0||form.name.trim().length<2}>{busy?t('common.saving'):t('common.save')}</Button></>}><div className="form-grid cols-2"><FormField label={t('catalog.code')}required><input value={form.code}onChange={(event)=>setForm({...form,code:event.target.value.toUpperCase()})}/></FormField><FormField label={t('catalog.service')}required><input value={form.name}onChange={(event)=>setForm({...form,name:event.target.value})}/></FormField><FormField label={t('catalog.category')}><input value={form.category}onChange={(event)=>setForm({...form,category:event.target.value})}/></FormField><FormField label={t('catalog.fee')}required><input type="number"min="0"step="0.01"value={(form.defaultFeeMinor/100).toFixed(2)}onChange={(event)=>setForm({...form,defaultFeeMinor:Math.round(Number(event.target.value||0)*100)})}/></FormField><FormField label={t('catalog.duration')}><div className="input-suffix"><input type="number"min="5"step="5"value={form.durationMinutes}onChange={(event)=>setForm({...form,durationMinutes:Number(event.target.value)})}/><span>{t('settings.minutes')}</span></div></FormField><FormField label={t('catalog.tax')}><div className="input-suffix"><input type="number"min="0"max="100"step="0.01"value={form.taxRate}onChange={(event)=>setForm({...form,taxRate:Number(event.target.value)})}/><span>%</span></div></FormField><FormField label={t('admin.description')}className="span-2"><textarea rows={3}value={form.description}onChange={(event)=>setForm({...form,description:event.target.value})}/></FormField>{item&&<label className="toggle-row span-2"><span><BookOpenCheck/><b>{t('catalog.active')}</b></span><input type="checkbox"checked={form.active}onChange={(event)=>setForm({...form,active:event.target.checked})}/></label>}</div></Modal>}
