import React,{useEffect,useId,useRef}from'react';
import{AlertCircle,CheckCircle2,ChevronLeft,ChevronRight,Inbox,Info,LoaderCircle,X}from'lucide-react';
import{createPortal}from'react-dom';
import{useTranslation}from'react-i18next';
import{useApp}from'../context/AppContext';

export function Button({variant='primary',size='md',icon:Icon,children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'|'quiet';size?:'sm'|'md'|'lg';icon?:React.ElementType}){return<button {...props}className={`btn btn-${variant} btn-${size} ${props.className??''}`}>{Icon&&<Icon size={size==='sm'?15:17}aria-hidden/>}<span>{children}</span></button>}
export function IconButton({label,icon:Icon,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{label:string;icon:React.ElementType}){return<button {...props}className={`icon-btn ${props.className??''}`}title={label}aria-label={label}><Icon size={18}/></button>}
export function PageHeader({title,subtitle,actions,eyebrow}: {title:string;subtitle?:string;actions?:React.ReactNode;eyebrow?:string}){return<header className="page-header"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</header>}
export function Card({children,className='',title,action}: {children:React.ReactNode;className?:string;title?:string;action?:React.ReactNode}){return<section className={`card ${className}`}>{(title||action)&&<header className="card-header"><h2>{title}</h2>{action}</header>}{children}</section>}
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'blue'|'green'|'amber'|'red'|'teal'}){return<span className={`badge badge-${tone}`}>{children}</span>}
export function statusTone(status:string):'neutral'|'blue'|'green'|'amber'|'red'|'teal'{if(['active','completed','paid','verified','success'].includes(status))return'green';if(['scheduled','issued','in_consultation','open'].includes(status))return'blue';if(['waiting','partially_paid','overdue','warning','draft'].includes(status))return'amber';if(['cancelled','void','failed','error','archived','no_show'].includes(status))return'red';if(['confirmed','recorded'].includes(status))return'teal';return'neutral';}
export function EmptyState({title,body,action,icon:Icon=Inbox,compact=false}:{title:string;body:string;action?:React.ReactNode;icon?:React.ElementType;compact?:boolean}){return<div className={`empty-state ${compact?'compact':''}`}><div className="empty-icon"><Icon size={compact?22:28}/></div><h3>{title}</h3><p>{body}</p>{action&&<div>{action}</div>}</div>}
export function LoadingState({label}:{label?:string}){const{t}=useTranslation();return<div className="loading-state"><LoaderCircle className="spin"size={24}/><span>{label??t('common.loading')}</span></div>}
export function ErrorState({message,onRetry}:{message:string;onRetry?:()=>void}){const{t}=useTranslation();return<div className="error-state"><AlertCircle size={26}/><div><b>{t('common.error')}</b><p>{message}</p>{onRetry&&<Button size="sm"variant="secondary"onClick={onRetry}>{t('common.retry')}</Button>}</div></div>}
export function FormField({label,required,hint,error,children,className=''}:{label:string;required?:boolean;hint?:string;error?:string;children:React.ReactNode;className?:string}){const id=useId();return<label className={`form-field ${className}`}data-field-id={id}><span className="field-label">{label}{required&&<sup>*</sup>}</span>{children}{hint&&<small className="field-hint">{hint}</small>}{error&&<small className="field-error">{error}</small>}</label>}
export function Modal({open,onClose,title,subtitle,children,footer,size='md',danger=false}:{open:boolean;onClose:()=>void;title:string;subtitle?:string;children:React.ReactNode;footer?:React.ReactNode;size?:'sm'|'md'|'lg'|'xl'|'full';danger?:boolean}){const{t}=useTranslation();const panel=useRef<HTMLDivElement>(null);useEffect(()=>{if(!open)return;const before=document.activeElement as HTMLElement|null;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();if(event.key==='Tab'&&panel.current){const focusable=[...panel.current.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0]!,last=focusable[focusable.length-1]!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener('keydown',onKey);document.body.classList.add('modal-open');window.setTimeout(()=>panel.current?.querySelector<HTMLElement>('input,select,textarea,button')?.focus(),0);return()=>{document.removeEventListener('keydown',onKey);document.body.classList.remove('modal-open');before?.focus();};},[open,onClose]);if(!open)return null;return createPortal(<div className="modal-backdrop"role="presentation"onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><div className={`modal modal-${size} ${danger?'modal-danger':''}`}role="dialog"aria-modal="true"aria-labelledby="modal-title"ref={panel}><header className="modal-header"><div><h2 id="modal-title">{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><IconButton label={t('common.close')}icon={X}onClick={onClose}/></header><div className="modal-body">{children}</div>{footer&&<footer className="modal-footer">{footer}</footer>}</div></div>,document.body);}
export function ConfirmDialog({open,onClose,onConfirm,title,body,confirmLabel,danger=false,busy=false}:{open:boolean;onClose:()=>void;onConfirm:()=>void;title:string;body:string;confirmLabel:string;danger?:boolean;busy?:boolean}){const{t}=useTranslation();return<Modal open={open}onClose={onClose}title={title}size="sm"danger={danger}footer={<><Button variant="secondary"onClick={onClose}disabled={busy}>{t('common.cancel')}</Button><Button variant={danger?'danger':'primary'}onClick={onConfirm}disabled={busy}>{busy?<LoaderCircle className="spin"size={16}/>:null}{confirmLabel}</Button></>}><p className="confirm-copy">{body}</p></Modal>}
export function Pagination({page,totalPages,total,onChange}:{page:number;totalPages:number;total:number;onChange:(page:number)=>void}){const{t}=useTranslation();if(totalPages<=1)return<div className="pagination single"><span>{total} {t('common.records')}</span></div>;return<div className="pagination"><span>{total} {t('common.records')}</span><div><IconButton label={t('ui.previousPage')}icon={ChevronLeft}disabled={page<=1}onClick={()=>onChange(page-1)}/><span>{t('common.page')} {page} {t('common.of')} {totalPages}</span><IconButton label={t('ui.nextPage')}icon={ChevronRight}disabled={page>=totalPages}onClick={()=>onChange(page+1)}/></div></div>}
export function ToastViewport(){const{t}=useTranslation();const{toasts,dismissToast}=useApp();return<div className="toast-viewport"aria-live="polite">{toasts.map((toast)=>{const Icon=toast.type==='success'?CheckCircle2:toast.type==='error'?AlertCircle:Info;return<div key={toast.id}className={`toast toast-${toast.type}`}><Icon size={19}/><span>{toast.message}</span><button aria-label={t('ui.dismiss')}onClick={()=>dismissToast(toast.id)}><X size={15}/></button></div>})}</div>}
export function Money({minor,symbol='৳'}:{minor:number;symbol?:string}){const{language}=useApp();return<span className="money">{symbol}{new Intl.NumberFormat(language==='bn'?'bn-BD':'en-BD',{minimumFractionDigits:2,maximumFractionDigits:2}).format((minor||0)/100)}</span>}
export function DateText({value,withTime=false}:{value?:string|null;withTime?:boolean}){const{language}=useApp();if(!value)return<span className="muted">—</span>;const d=new Date(value);if(Number.isNaN(d.getTime()))return<span>{value}</span>;return<>{new Intl.DateTimeFormat(language==='bn'?'bn-BD':'en-BD',withTime?{dateStyle:'medium',timeStyle:'short'}:{dateStyle:'medium'}).format(d)}</>}
export function SkeletonRows({rows=5,columns=5}:{rows?:number;columns?:number}){return<div className="skeleton-table">{Array.from({length:rows},(_,r)=><div key={r}>{Array.from({length:columns},(_,c)=><span key={c}style={{width:`${50+((r+c)*17)%45}%`}}/>)}</div>)}</div>}
export function Segmented({value,onChange,options}:{value:string;onChange:(value:string)=>void;options:Array<{value:string;label:string}>}){return<div className="segmented"role="tablist">{options.map((option)=><button key={option.value}role="tab"aria-selected={value===option.value}className={value===option.value?'active':''}onClick={()=>onChange(option.value)}>{option.label}</button>)}</div>}
