import { createCipheriv, createDecipheriv, createHash, pbkdf2Sync, randomBytes, randomUUID } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import { pipeline } from 'node:stream/promises';
import archiver from 'archiver';
import yauzl, { type Entry, type ZipFile } from 'yauzl';
import type { BackupAnalysis, BackupRecord, RestoreSelection } from '../../shared/types.js';
import type { DentivaDatabase } from '../database/database.js';
import { mapBackup } from '../database/mappers.js';
import type { AuditService } from '../security/security.js';
import type { DentivaPaths } from '../utils/paths.js';
import type { AppLogger } from '../utils/logger.js';
import { AppError } from '../utils/errors.js';

const PACKAGE_VERSION='1.0';
const ENCRYPTION_MARKER=Buffer.from('DENTIVAENC1\0','ascii');
const ENCRYPTION_ITERATIONS=310_000;

interface ManifestFile{path:string;size:number;sha256:string;category:'database'|'attachment'|'branding'|'configuration'}
interface BackupManifest{format:'Dentiva Backup';packageVersion:string;appVersion:string;schemaVersion:number;createdAt:string;clinicId:string;encrypted:boolean;files:ManifestFile[];counts:Record<string,number>}
interface ExtractedPackage{directory:string;manifest:BackupManifest;databasePath:string;encrypted:boolean}
interface RestoreResult{imported:Record<string,number>;skipped:Record<string,number>}

async function sha256File(file:string):Promise<string>{const hash=createHash('sha256');await pipeline(fs.createReadStream(file),hash as unknown as NodeJS.WritableStream);return hash.digest('hex');}

export class BackupService{
  constructor(private readonly db:DentivaDatabase,private readonly paths:DentivaPaths,private readonly audit:AuditService,private readonly logger:AppLogger,private readonly appVersion:string){}

  list(clinicId:string):BackupRecord[]{return this.db.all<Record<string,unknown>>('SELECT * FROM backup_records WHERE clinic_id=? ORDER BY created_at DESC LIMIT 200',clinicId).map(mapBackup);}

  async create(clinicId:string,userId:string,userName:string,input:{destination?:string;encryptPassword?:string;type?:'manual'|'scheduled'}):Promise<BackupRecord>{
    if(input.encryptPassword&&input.encryptPassword.length<10)throw new AppError('WEAK_BACKUP_PASSWORD','Use at least 10 characters for the backup password.');
    const destinationDir=path.resolve(input.destination||this.paths.backups);fs.mkdirSync(destinationDir,{recursive:true,mode:0o700});
    const id=randomUUID();const now=new Date();const stamp=now.toISOString().replace(/[:.]/g,'-');const encrypted=Boolean(input.encryptPassword);
    const fileName=`Dentiva-${stamp}${encrypted?'-Encrypted':''}.dentivabackup`;const finalPath=path.join(destinationDir,fileName);const work=path.join(this.paths.temp,`backup-${id}`);fs.mkdirSync(work,{recursive:true,mode:0o700});
    this.db.run(`INSERT INTO backup_records(id,clinic_id,file_name,file_path,backup_type,size_bytes,encrypted,status,checksum,created_at,verified_at,error_summary) VALUES(?,?,?,?,?,0,?,'running',NULL,?,NULL,NULL)`,id,clinicId,fileName,finalPath,input.type??'manual',encrypted?1:0,now.toISOString());
    try{
      this.db.checkpoint();const snapshot=path.join(work,'dentiva.db');this.db.exec(`VACUUM INTO '${snapshot.replaceAll("'","''")}'`);
      const files:ManifestFile[]=[{path:'database/dentiva.db',size:fs.statSync(snapshot).size,sha256:await sha256File(snapshot),category:'database'}];
      const attachmentRows=this.db.all<{relative_path:string;size_bytes:number;sha256:string}>('SELECT relative_path,size_bytes,sha256 FROM attachments WHERE clinic_id=? ORDER BY relative_path',clinicId);
      for(const row of attachmentRows){
        const source=this.paths.resolveAttachment(row.relative_path);if(!fs.existsSync(source))throw new AppError('BACKUP_FILE_MISSING',`Backup stopped because a managed attachment is missing: ${path.basename(row.relative_path)}.`);
        const actualSize=fs.statSync(source).size;const actualHash=await sha256File(source);if(actualHash!==row.sha256)this.logger.warn('Attachment checksum changed before backup',{relativePath:row.relative_path});
        files.push({path:`attachments/${row.relative_path.replaceAll(path.sep,'/')}`,size:actualSize,sha256:actualHash,category:'attachment'});
      }
      if(fs.existsSync(this.paths.branding))for(const entry of fs.readdirSync(this.paths.branding,{withFileTypes:true})){if(!entry.isFile())continue;const source=path.join(this.paths.branding,entry.name);files.push({path:`branding/${entry.name}`,size:fs.statSync(source).size,sha256:await sha256File(source),category:'branding'});}
      const counts=this.counts(this.db,clinicId);const manifest:BackupManifest={format:'Dentiva Backup',packageVersion:PACKAGE_VERSION,appVersion:this.appVersion,schemaVersion:this.db.schemaVersion,createdAt:now.toISOString(),clinicId,encrypted,files,counts};
      const manifestPath=path.join(work,'manifest.json');fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2),{encoding:'utf8',mode:0o600});
      const plainArchive=path.join(work,'package.zip');await this.writeArchive(plainArchive,manifestPath,snapshot,files);
      if(input.encryptPassword)await this.encryptFile(plainArchive,finalPath,input.encryptPassword);else fs.renameSync(plainArchive,finalPath);
      const verification=await this.verifyFile(finalPath,input.encryptPassword);if(!verification.valid)throw new AppError('BACKUP_VERIFICATION_FAILED',verification.details);
      const checksum=await sha256File(finalPath);const size=fs.statSync(finalPath).size;const verifiedAt=new Date().toISOString();
      this.db.run("UPDATE backup_records SET size_bytes=?,status='verified',checksum=?,verified_at=? WHERE id=?",size,checksum,verifiedAt,id);
      this.audit.record({clinicId,userId,userName,action:'backup_created',entityType:'backup',entityIdentifier:id,summary:`Verified ${encrypted?'encrypted ':''}backup created (${size} bytes)`});
      return mapBackup(this.db.get<Record<string,unknown>>('SELECT * FROM backup_records WHERE id=?',id)!);
    }catch(error){fs.rmSync(finalPath,{force:true});this.db.run("UPDATE backup_records SET status='failed',error_summary=? WHERE id=?",error instanceof Error?error.message.slice(0,500):'Backup failed',id);this.audit.record({clinicId,userId,userName,action:'backup_created',entityType:'backup',entityIdentifier:id,summary:'Backup creation failed',outcome:'failure'});throw error;}
    finally{fs.rmSync(work,{recursive:true,force:true});}
  }

  async verifyFile(packagePath:string,password?:string):Promise<{valid:boolean;details:string}>{
    let extracted:ExtractedPackage|undefined;
    try{extracted=await this.extractAndVerify(packagePath,password);const check=new DatabaseSync(extracted.databasePath,{readOnly:true});const result=check.prepare('PRAGMA integrity_check').get() as Record<string,unknown>;const integrity=String(Object.values(result)[0]);const foreign=check.prepare('PRAGMA foreign_key_check').all();check.close();if(integrity!=='ok'||foreign.length)throw new Error('The database inside the backup failed integrity validation.');return{valid:true,details:'Manifest, file checksums, database integrity, and foreign keys are valid.'};}
    catch(error){return{valid:false,details:error instanceof Error?error.message:'Backup validation failed.'};}
    finally{if(extracted)fs.rmSync(extracted.directory,{recursive:true,force:true});}
  }

  async analyze(packagePath:string,password?:string):Promise<BackupAnalysis>{
    const extracted=await this.extractAndVerify(packagePath,password);let source:DatabaseSync|undefined;
    try{source=new DatabaseSync(extracted.databasePath,{readOnly:true});const counts=this.counts(source,undefined);const patients=(source.prepare(`SELECT id,patient_code,full_name,phone,registration_date FROM patients ORDER BY full_name`).all() as Array<Record<string,unknown>>).map((r)=>({id:String(r.id),patientCode:String(r.patient_code),fullName:String(r.full_name),phone:String(r.phone),registrationDate:String(r.registration_date)}));
      const bounds:Record<string,{from:string|null;to:string|null}>={};for(const [name,table,column] of [['visits','visits','visited_at'],['invoices','invoices','issued_at'],['payments','payments','paid_at'],['expenses','expenses','expense_date'],['appointments','appointments','start_at']] as const){const row=source.prepare(`SELECT min(${column}) AS min,max(${column}) AS max FROM ${table}`).get() as Record<string,unknown>;bounds[name]={from:row.min?String(row.min):null,to:row.max?String(row.max):null};}
      return{packageVersion:extracted.manifest.packageVersion,appVersion:extracted.manifest.appVersion,createdAt:extracted.manifest.createdAt,encrypted:extracted.encrypted,checksumValid:true,counts,patients,dateBounds:bounds};
    }finally{source?.close();fs.rmSync(extracted.directory,{recursive:true,force:true});}
  }

  async restore(clinicId:string,userId:string,userName:string,packagePath:string,selection:RestoreSelection):Promise<RestoreResult>{
    const extracted=await this.extractAndVerify(packagePath,selection.password);const jobId=randomUUID();const now=new Date().toISOString();
    this.db.run(`INSERT INTO import_jobs(id,clinic_id,source_path,package_version,mode,duplicate_strategy,status,selection_json,result_json,started_at,completed_at,error_summary,created_by) VALUES(?,?,?,?,?,?,'running',?,'{}',?,NULL,NULL,?)`,jobId,clinicId,path.resolve(packagePath),extracted.manifest.packageVersion,selection.modules.includes('all')?'full':'selective',selection.duplicateStrategy,JSON.stringify({...selection,password:selection.password?'[protected]':undefined}),now,userId);
    try{
      let result:RestoreResult;let auditUserId:string|null=userId;
      if(selection.modules.includes('all')){await this.fullRestore(extracted);result={imported:{all:Object.values(extracted.manifest.counts).reduce((a,b)=>a+b,0)},skipped:{}};auditUserId=this.db.get<{id:string}>('SELECT id FROM users WHERE id=?',userId)?.id??null;this.db.run(`INSERT OR IGNORE INTO import_jobs(id,clinic_id,source_path,package_version,mode,duplicate_strategy,status,selection_json,result_json,started_at,completed_at,error_summary,created_by) VALUES(?,?,?,?,?,?,'running',?,'{}',?,NULL,NULL,?)`,jobId,clinicId,path.resolve(packagePath),extracted.manifest.packageVersion,'full',selection.duplicateStrategy,JSON.stringify({...selection,password:selection.password?'[protected]':undefined}),now,auditUserId);}
      else result=await this.selectiveRestore(clinicId,extracted,selection);
      this.db.run("UPDATE import_jobs SET status='completed',result_json=?,completed_at=? WHERE id=?",JSON.stringify(result),new Date().toISOString(),jobId);
      this.audit.record({clinicId,userId:auditUserId,userName,action:'backup_restored',entityType:'import_job',entityIdentifier:jobId,summary:`${selection.modules.includes('all')?'Full':'Selective'} backup restore completed`});return result;
    }catch(error){this.db.run("UPDATE import_jobs SET status='rolled_back',error_summary=?,completed_at=? WHERE id=?",error instanceof Error?error.message.slice(0,500):'Restore failed',new Date().toISOString(),jobId);this.audit.record({clinicId,userId:this.db.get<{id:string}>('SELECT id FROM users WHERE id=?',userId)?.id??null,userName,action:'backup_restored',entityType:'import_job',entityIdentifier:jobId,summary:'Backup restore failed and data changes were rolled back',outcome:'failure'});throw error;}
    finally{fs.rmSync(extracted.directory,{recursive:true,force:true});}
  }

  private async fullRestore(extracted:ExtractedPackage):Promise<void>{
    if(extracted.manifest.schemaVersion!==this.db.schemaVersion)throw new AppError('BACKUP_VERSION_INCOMPATIBLE','This Dentiva version can fully restore backups created with the same database schema. Use selective restore for compatible records.');
    const currentClinic=this.db.get<{id:string}>('SELECT id FROM clinics LIMIT 1');if(currentClinic&&currentClinic.id!==extracted.manifest.clinicId)throw new AppError('BACKUP_CLINIC_MISMATCH','Complete workspace replacement is only available for a backup of this clinic. Use selective restore to import records from another clinic.');
    const suffix=`${Date.now()}-${randomUUID()}`;const attachmentStage=path.join(this.paths.root,`Attachments.restore-${suffix}`);const attachmentOld=path.join(this.paths.root,`Attachments.before-restore-${suffix}`);const brandingStage=path.join(this.paths.root,`Branding.restore-${suffix}`);const brandingOld=path.join(this.paths.root,`Branding.before-restore-${suffix}`);const databaseRollback=path.join(this.paths.temp,`database-before-full-restore-${suffix}.db`);
    fs.mkdirSync(attachmentStage,{recursive:true,mode:0o700});fs.mkdirSync(brandingStage,{recursive:true,mode:0o700});const extractedAttachments=path.join(extracted.directory,'attachments');const extractedBranding=path.join(extracted.directory,'branding');if(fs.existsSync(extractedAttachments))fs.cpSync(extractedAttachments,attachmentStage,{recursive:true,errorOnExist:false});if(fs.existsSync(extractedBranding))fs.cpSync(extractedBranding,brandingStage,{recursive:true,errorOnExist:false});this.db.checkpoint();this.db.exec(`VACUUM INTO '${databaseRollback.replaceAll("'","''")}'`);
    let attachmentsSwapped=false;let brandingSwapped=false;let databaseReplaced=false;
    try{
      if(fs.existsSync(this.paths.attachments))fs.renameSync(this.paths.attachments,attachmentOld);fs.renameSync(attachmentStage,this.paths.attachments);attachmentsSwapped=true;
      if(fs.existsSync(this.paths.branding))fs.renameSync(this.paths.branding,brandingOld);fs.renameSync(brandingStage,this.paths.branding);brandingSwapped=true;
      this.db.replaceWith(extracted.databasePath);databaseReplaced=true;const logo=this.db.get<{id:string;logo_path:string|null}>('SELECT id,logo_path FROM clinics LIMIT 1');if(logo?.logo_path){const candidate=path.join(this.paths.branding,path.basename(logo.logo_path));this.db.run('UPDATE clinics SET logo_path=? WHERE id=?',fs.existsSync(candidate)?candidate:null,logo.id);}if(this.db.integrityCheck()!=='ok'||this.db.foreignKeyCheck().length)throw new AppError('RESTORE_INTEGRITY_FAILED','The restored workspace did not pass final integrity validation.');
      fs.rmSync(attachmentOld,{recursive:true,force:true});fs.rmSync(brandingOld,{recursive:true,force:true});fs.rmSync(databaseRollback,{force:true});
    }catch(error){
      if(databaseReplaced)try{this.db.replaceWith(databaseRollback);}catch(rollbackError){this.logger.error('Full restore database rollback failed; a safety database was retained',rollbackError);}
      if(attachmentsSwapped){try{fs.rmSync(this.paths.attachments,{recursive:true,force:true});if(fs.existsSync(attachmentOld))fs.renameSync(attachmentOld,this.paths.attachments);}catch(rollbackError){this.logger.error('Full restore attachment rollback failed; the previous attachment directory was retained',rollbackError);}}
      if(brandingSwapped){try{fs.rmSync(this.paths.branding,{recursive:true,force:true});if(fs.existsSync(brandingOld))fs.renameSync(brandingOld,this.paths.branding);}catch(rollbackError){this.logger.error('Full restore branding rollback failed; the previous branding directory was retained',rollbackError);}}
      throw error;
    }finally{fs.rmSync(attachmentStage,{recursive:true,force:true});fs.rmSync(brandingStage,{recursive:true,force:true});}
  }

  private async selectiveRestore(clinicId:string,extracted:ExtractedPackage,selection:RestoreSelection):Promise<RestoreResult>{
    const source=new DatabaseSync(extracted.databasePath,{readOnly:true});const imported:Record<string,number>={};const skipped:Record<string,number>={};const modules=new Set(selection.modules);const patientMap=new Map<string,string>();const staffMap=new Map<string,string>();const appointmentMap=new Map<string,string>();const treatmentMap=new Map<string,string>();const visitMap=new Map<string,string>();const invoiceMap=new Map<string,string>();const referralMap=new Map<string,string>();const paymentMap=new Map<string,string>();const filesToCopy:Array<{from:string;to:string}>=[];const copiedFiles:string[]=[];const replacedFiles:Array<{backup:string;target:string}>=[];const fileRollbackDirectory=path.join(this.paths.temp,`selective-restore-files-${randomUUID()}`);
    const inc=(bucket:Record<string,number>,key:string)=>bucket[key]=(bucket[key]??0)+1;const hasSourceTable=(name:string)=>Boolean(source.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(name));
    const sourceClinic=source.prepare('SELECT id FROM clinics LIMIT 1').get() as {id:string}|undefined;if(!sourceClinic){source.close();throw new AppError('INVALID_BACKUP','The backup does not contain clinic data.');}
    const selectedIds=new Set(selection.patientIds??[]);const patientRows=source.prepare(`SELECT * FROM patients ${selectedIds.size?`WHERE id IN (${[...selectedIds].map(()=>'?').join(',')})`:''}`).all(...[...selectedIds]) as Array<Record<string,unknown>>;
    const patientCode=(sourceId:string)=>String((source.prepare('SELECT patient_code FROM patients WHERE id=?').get(sourceId) as Record<string,unknown>|undefined)?.patient_code??'');
    const resolveExistingPatient=(sourceId:string):string|undefined=>{if(patientMap.has(sourceId))return patientMap.get(sourceId);const code=patientCode(sourceId);const row=code?this.db.get<{id:string}>('SELECT id FROM patients WHERE clinic_id=? AND patient_code=? COLLATE NOCASE',clinicId,code):undefined;if(row){patientMap.set(sourceId,row.id);return row.id;}return undefined;};
    try{
      this.db.transaction(()=>{
        if(modules.has('staff')){for(const row of source.prepare('SELECT * FROM staff').all() as Array<Record<string,unknown>>){const existing=this.db.get<{id:string}>('SELECT id FROM staff WHERE clinic_id=? AND staff_code=? COLLATE NOCASE',clinicId,String(row.staff_code));const target=this.chooseTarget(String(row.id),existing?.id,selection.duplicateStrategy);staffMap.set(String(row.id),target.id);if(target.skip){inc(skipped,'staff');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId};if(target.copy)copy.staff_code=this.uniqueCode('staff','staff_code',String(row.staff_code));this.insertRaw('staff',copy,target.update);inc(imported,'staff');}for(const [sourceStaff,targetStaff] of staffMap){for(const row of source.prepare('SELECT * FROM staff_salary_history WHERE staff_id=?').all(sourceStaff) as Array<Record<string,unknown>>){const target=this.chooseTarget(String(row.id),this.db.get<{id:string}>('SELECT id FROM staff_salary_history WHERE id=?',String(row.id))?.id,selection.duplicateStrategy);if(target.skip){inc(skipped,'salaryHistory');continue;}this.insertRaw('staff_salary_history',{...row,id:target.id,staff_id:targetStaff},target.update);inc(imported,'salaryHistory');}}}
        if(modules.has('treatments'))for(const row of source.prepare('SELECT * FROM treatment_catalog').all() as Array<Record<string,unknown>>){const existing=this.db.get<{id:string}>('SELECT id FROM treatment_catalog WHERE clinic_id=? AND code=? COLLATE NOCASE',clinicId,String(row.code));const target=this.chooseTarget(String(row.id),existing?.id,selection.duplicateStrategy);treatmentMap.set(String(row.id),target.id);if(target.skip){inc(skipped,'treatments');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId};if(target.copy)copy.code=this.uniqueCode('treatment_catalog','code',String(row.code));this.insertRaw('treatment_catalog',copy,target.update);inc(imported,'treatments');}
        if(modules.has('patients'))for(const row of patientRows){const existing=this.db.get<{id:string}>('SELECT id FROM patients WHERE clinic_id=? AND (id=? OR patient_code=? COLLATE NOCASE) LIMIT 1',clinicId,String(row.id),String(row.patient_code));const target=this.chooseTarget(String(row.id),existing?.id,selection.duplicateStrategy);patientMap.set(String(row.id),target.id);if(target.skip){inc(skipped,'patients');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId};if(target.copy)copy.patient_code=this.uniqueCode('patients','patient_code',String(row.patient_code));this.insertRaw('patients',copy,target.update);inc(imported,'patients');}
        else for(const id of selectedIds){if(!resolveExistingPatient(id))throw new AppError('RESTORE_DEPENDENCY_MISSING',`Patient ${patientCode(id)||id} must exist before restoring related records. Include Patients or change the selection.`);}

        const selectedPatientSourceIds=selectedIds.size?[...selectedIds]:patientRows.map((r)=>String(r.id));const patientFilter=selectedPatientSourceIds.length?` WHERE patient_id IN (${selectedPatientSourceIds.map(()=>'?').join(',')})`:'';
        const ensurePatient=(id:string):string=>{const target=resolveExistingPatient(id);if(!target)throw new AppError('RESTORE_DEPENDENCY_MISSING',`Related patient ${patientCode(id)||id} is missing. Include the patient in the restore selection.`);return target;};
        const mapStaff=(id:unknown):string|null=>{if(!id)return null;const sid=String(id);if(staffMap.has(sid))return staffMap.get(sid)!;return this.db.get<{id:string}>('SELECT id FROM staff WHERE id=?',sid)?.id??null;};

        if(modules.has('appointments'))for(const row of source.prepare(`SELECT * FROM appointments${patientFilter}`).all(...selectedPatientSourceIds) as Array<Record<string,unknown>>){const target=this.chooseTarget(String(row.id),this.db.get<{id:string}>('SELECT id FROM appointments WHERE id=?',String(row.id))?.id,selection.duplicateStrategy);appointmentMap.set(String(row.id),target.id);if(target.skip){inc(skipped,'appointments');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId,patient_id:ensurePatient(String(row.patient_id)),dentist_id:mapStaff(row.dentist_id),rescheduled_from_id:null};if(target.copy)copy.appointment_code=this.uniqueCode('appointments','appointment_code',String(row.appointment_code));this.insertRaw('appointments',copy,target.update);inc(imported,'appointments');}

        if(modules.has('visits')||modules.has('clinical_records'))for(const row of source.prepare(`SELECT * FROM visits${patientFilter}`).all(...selectedPatientSourceIds) as Array<Record<string,unknown>>){const target=this.chooseTarget(String(row.id),this.db.get<{id:string}>('SELECT id FROM visits WHERE id=?',String(row.id))?.id,selection.duplicateStrategy);visitMap.set(String(row.id),target.id);if(target.skip){inc(skipped,'visits');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId,patient_id:ensurePatient(String(row.patient_id)),appointment_id:row.appointment_id?(appointmentMap.get(String(row.appointment_id))??this.db.get<{id:string}>('SELECT id FROM appointments WHERE id=?',String(row.appointment_id))?.id??null):null,provider_id:mapStaff(row.provider_id)};if(target.copy)copy.visit_number=this.uniqueCode('visits','visit_number',String(row.visit_number));this.insertRaw('visits',copy,target.update);inc(imported,'visits');}
        const mapVisit=(id:unknown):string|null=>id?(visitMap.get(String(id))??this.db.get<{id:string}>('SELECT id FROM visits WHERE id=?',String(id))?.id??null):null;

        if(modules.has('clinical_records')){
          for(const table of ['clinical_notes','diagnoses','visit_treatments'] as const)for(const row of source.prepare(`SELECT x.* FROM ${table} x JOIN visits v ON v.id=x.visit_id${patientFilter?patientFilter.replace(' WHERE ',' WHERE v.') :''}`).all(...selectedPatientSourceIds) as Array<Record<string,unknown>>){const mapped=mapVisit(row.visit_id);if(!mapped){inc(skipped,table);continue;}const copy:Record<string,unknown>={...row,id:selection.duplicateStrategy==='copy'?randomUUID():row.id,visit_id:mapped};if(table==='clinical_notes')copy.author_id=null;if(table==='diagnoses')copy.recorded_by=null;if(table==='visit_treatments'){copy.provider_id=mapStaff(row.provider_id);copy.treatment_id=null;}const exists=this.db.get('SELECT id FROM '+table+' WHERE id=?',String(copy.id));if(exists&&selection.duplicateStrategy==='skip'){inc(skipped,table);continue;}this.insertRaw(table,copy,Boolean(exists)&&selection.duplicateStrategy==='update');inc(imported,table);}
          for(const row of source.prepare(`SELECT * FROM dental_chart_entries${patientFilter}`).all(...selectedPatientSourceIds) as Array<Record<string,unknown>>){const copy:Record<string,unknown>={...row,id:selection.duplicateStrategy==='copy'?randomUUID():row.id,patient_id:ensurePatient(String(row.patient_id)),visit_id:mapVisit(row.visit_id),recorded_by:null};const exists=this.db.get('SELECT id FROM dental_chart_entries WHERE id=?',String(copy.id));if(exists&&selection.duplicateStrategy==='skip'){inc(skipped,'dentalChart');continue;}this.insertRaw('dental_chart_entries',copy,Boolean(exists)&&selection.duplicateStrategy==='update');inc(imported,'dentalChart');}
        }

        if(modules.has('referrals')||modules.has('clinical_records'))for(const row of source.prepare(`SELECT * FROM referrals${patientFilter}`).all(...selectedPatientSourceIds) as Array<Record<string,unknown>>){const target=this.chooseTarget(String(row.id),this.db.get<{id:string}>('SELECT id FROM referrals WHERE id=?',String(row.id))?.id,selection.duplicateStrategy);referralMap.set(String(row.id),target.id);if(target.skip){inc(skipped,'referrals');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId,patient_id:ensurePatient(String(row.patient_id)),visit_id:mapVisit(row.visit_id)};if(target.copy)copy.referral_number=this.uniqueCode('referrals','referral_number',String(row.referral_number));this.insertRaw('referrals',copy,target.update);inc(imported,'referrals');}

        if(modules.has('treatment_plans')&&hasSourceTable('treatment_plans'))for(const row of source.prepare(`SELECT * FROM treatment_plans${patientFilter}`).all(...selectedPatientSourceIds) as Array<Record<string,unknown>>){const oldId=String(row.id);const target=this.chooseTarget(oldId,this.db.get<{id:string}>('SELECT id FROM treatment_plans WHERE id=?',oldId)?.id,selection.duplicateStrategy);if(target.skip){inc(skipped,'treatmentPlans');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId,patient_id:ensurePatient(String(row.patient_id)),visit_id:mapVisit(row.visit_id),provider_id:mapStaff(row.provider_id)};if(target.copy)copy.plan_number=this.uniqueCode('treatment_plans','plan_number',String(row.plan_number));this.insertRaw('treatment_plans',copy,target.update);for(const item of source.prepare('SELECT * FROM treatment_plan_items WHERE plan_id=?').all(oldId) as Array<Record<string,unknown>>){const itemId=target.copy?randomUUID():String(item.id);const exists=this.db.get('SELECT id FROM treatment_plan_items WHERE id=?',itemId);const mappedTreatment=item.treatment_id?(treatmentMap.get(String(item.treatment_id))??this.db.get<{id:string}>('SELECT id FROM treatment_catalog WHERE id=?',String(item.treatment_id))?.id??null):null;this.insertRaw('treatment_plan_items',{...item,id:itemId,plan_id:target.id,treatment_id:mappedTreatment},Boolean(exists)&&selection.duplicateStrategy==='update',selection.duplicateStrategy==='skip');}inc(imported,'treatmentPlans');}

        if(modules.has('prescriptions'))for(const row of source.prepare(`SELECT * FROM prescriptions${patientFilter}`).all(...selectedPatientSourceIds) as Array<Record<string,unknown>>){const oldId=String(row.id);const target=this.chooseTarget(oldId,this.db.get<{id:string}>('SELECT id FROM prescriptions WHERE id=?',oldId)?.id,selection.duplicateStrategy);if(target.skip){inc(skipped,'prescriptions');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId,patient_id:ensurePatient(String(row.patient_id)),visit_id:mapVisit(row.visit_id),provider_id:mapStaff(row.provider_id)};if(target.copy)copy.prescription_number=this.uniqueCode('prescriptions','prescription_number',String(row.prescription_number));this.insertRaw('prescriptions',copy,target.update);for(const item of source.prepare('SELECT * FROM prescription_items WHERE prescription_id=?').all(oldId) as Array<Record<string,unknown>>){this.insertRaw('prescription_items',{...item,id:target.copy?randomUUID():item.id,prescription_id:target.id},false,true);}inc(imported,'prescriptions');}

        const financialCondition=[`clinic_id=?`];const financialArgs:Array<string>=[sourceClinic.id];if(selection.financialFrom){financialCondition.push('substr(issued_at,1,10)>=?');financialArgs.push(selection.financialFrom);}if(selection.financialTo){financialCondition.push('substr(issued_at,1,10)<=?');financialArgs.push(selection.financialTo);}
        if(modules.has('invoices')||modules.has('payments'))for(const row of source.prepare(`SELECT * FROM invoices WHERE ${financialCondition.join(' AND ')}`).all(...financialArgs) as Array<Record<string,unknown>>){let patient:string;try{patient=ensurePatient(String(row.patient_id));}catch{inc(skipped,'invoices_dependency');continue;}const oldId=String(row.id);const target=this.chooseTarget(oldId,this.db.get<{id:string}>('SELECT id FROM invoices WHERE id=?',oldId)?.id,selection.duplicateStrategy);invoiceMap.set(oldId,target.id);if(target.skip){inc(skipped,'invoices');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId,patient_id:patient,visit_id:mapVisit(row.visit_id),created_by:null,voided_by:null};if(target.copy)copy.invoice_number=this.uniqueCode('invoices','invoice_number',String(row.invoice_number));this.insertRaw('invoices',copy,target.update);for(const item of source.prepare('SELECT * FROM invoice_items WHERE invoice_id=?').all(oldId) as Array<Record<string,unknown>>)this.insertRaw('invoice_items',{...item,id:target.copy?randomUUID():item.id,invoice_id:target.id,treatment_id:null},false,true);inc(imported,'invoices');}
        if(modules.has('payments'))for(const [oldInvoice,newInvoice] of invoiceMap){for(const row of source.prepare('SELECT * FROM payments WHERE invoice_id=?').all(oldInvoice) as Array<Record<string,unknown>>){if(selection.financialFrom&&String(row.paid_at).slice(0,10)<selection.financialFrom)continue;if(selection.financialTo&&String(row.paid_at).slice(0,10)>selection.financialTo)continue;const target=this.chooseTarget(String(row.id),this.db.get<{id:string}>('SELECT id FROM payments WHERE id=?',String(row.id))?.id,selection.duplicateStrategy);paymentMap.set(String(row.id),target.id);if(target.skip){inc(skipped,'payments');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId,invoice_id:newInvoice,received_by:null};if(target.copy)copy.receipt_number=this.uniqueCode('payments','receipt_number',String(row.receipt_number));this.insertRaw('payments',copy,target.update);for(const refund of source.prepare('SELECT * FROM refunds WHERE payment_id=?').all(String(row.id)) as Array<Record<string,unknown>>)this.insertRaw('refunds',{...refund,id:target.copy?randomUUID():refund.id,clinic_id:clinicId,payment_id:target.id,approved_by:null},false,true);inc(imported,'payments');}}

        if(modules.has('expenses')){let sql='SELECT * FROM expenses WHERE clinic_id=?';const args=[sourceClinic.id];if(selection.financialFrom){sql+=' AND expense_date>=?';args.push(selection.financialFrom);}if(selection.financialTo){sql+=' AND expense_date<=?';args.push(selection.financialTo);}for(const row of source.prepare(sql).all(...args) as Array<Record<string,unknown>>){let category=this.db.get<{id:string}>('SELECT id FROM expense_categories WHERE clinic_id=? AND name=(SELECT name FROM expense_categories WHERE id=?) COLLATE NOCASE',clinicId,String(row.category_id))?.id;if(!category){const sourceCategory=source.prepare('SELECT name FROM expense_categories WHERE id=?').get(String(row.category_id)) as {name:string};category=randomUUID();this.db.run('INSERT INTO expense_categories(id,clinic_id,name,active,sort_order) VALUES(?,?,?,1,999)',category,clinicId,sourceCategory.name);}const target=this.chooseTarget(String(row.id),this.db.get<{id:string}>('SELECT id FROM expenses WHERE id=?',String(row.id))?.id,selection.duplicateStrategy);if(target.skip){inc(skipped,'expenses');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId,category_id:category,created_by:null};if(target.copy)copy.expense_number=this.uniqueCode('expenses','expense_number',String(row.expense_number));this.insertRaw('expenses',copy,target.update);inc(imported,'expenses');}}

        if(modules.has('inventory')){
          for(const row of source.prepare('SELECT * FROM suppliers').all() as Array<Record<string,unknown>>){const existing=this.db.get<{id:string}>('SELECT id FROM suppliers WHERE clinic_id=? AND name=? COLLATE NOCASE',clinicId,String(row.name));if(existing){staffMap.set(`supplier:${String(row.id)}`,existing.id);continue;}const nid=randomUUID();staffMap.set(`supplier:${String(row.id)}`,nid);this.insertRaw('suppliers',{...row,id:nid,clinic_id:clinicId},false);inc(imported,'suppliers');}
          for(const row of source.prepare('SELECT * FROM inventory_categories').all() as Array<Record<string,unknown>>){const existing=this.db.get<{id:string}>('SELECT id FROM inventory_categories WHERE clinic_id=? AND name=? COLLATE NOCASE',clinicId,String(row.name));const nid=existing?.id??randomUUID();staffMap.set(`category:${String(row.id)}`,nid);if(!existing){this.insertRaw('inventory_categories',{...row,id:nid,clinic_id:clinicId},false);inc(imported,'inventoryCategories');}}
          for(const row of source.prepare('SELECT * FROM inventory_items').all() as Array<Record<string,unknown>>){const existing=this.db.get<{id:string}>('SELECT id FROM inventory_items WHERE clinic_id=? AND sku=? COLLATE NOCASE',clinicId,String(row.sku));const target=this.chooseTarget(String(row.id),existing?.id,selection.duplicateStrategy);if(target.skip){inc(skipped,'inventory');continue;}const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId,category_id:row.category_id?staffMap.get(`category:${String(row.category_id)}`)??null:null,supplier_id:row.supplier_id?staffMap.get(`supplier:${String(row.supplier_id)}`)??null:null};if(target.copy)copy.sku=this.uniqueCode('inventory_items','sku',String(row.sku));this.insertRaw('inventory_items',copy,target.update);inc(imported,'inventory');}
        }

        if(modules.has('attachments')||modules.has('documents'))for(const row of source.prepare(`SELECT * FROM attachments${patientFilter}`).all(...selectedPatientSourceIds) as Array<Record<string,unknown>>){let mappedPatient:string|null=null;if(row.patient_id){try{mappedPatient=ensurePatient(String(row.patient_id));}catch{inc(skipped,'attachments_dependency');continue;}}const target=this.chooseTarget(String(row.id),this.db.get<{id:string}>('SELECT id FROM attachments WHERE id=?',String(row.id))?.id,selection.duplicateStrategy);if(target.skip){inc(skipped,'attachments');continue;}const extension=String(row.extension);const relative=target.copy?path.join(mappedPatient??'clinic',new Date().getFullYear().toString(),String(new Date().getMonth()+1).padStart(2,'0'),`${target.id}.${extension}`):String(row.relative_path);const copy:Record<string,unknown>={...row,id:target.id,clinic_id:clinicId,patient_id:mappedPatient,visit_id:mapVisit(row.visit_id),invoice_id:row.invoice_id?invoiceMap.get(String(row.invoice_id))??null:null,referral_id:row.referral_id?referralMap.get(String(row.referral_id))??null:null,relative_path:relative,stored_name:path.basename(relative),created_by:null};this.insertRaw('attachments',copy,target.update);const from=path.join(extracted.directory,'attachments',String(row.relative_path));if(!fs.existsSync(from))throw new AppError('BACKUP_INCOMPLETE',`The attachment ${path.basename(String(row.relative_path))} is missing from this backup.`);filesToCopy.push({from,to:this.paths.resolveAttachment(relative)});inc(imported,'attachments');}

        if(modules.has('settings'))for(const row of source.prepare('SELECT key,value_json,updated_at FROM app_settings WHERE clinic_id=?').all(sourceClinic.id) as Array<Record<string,unknown>>)this.db.run(`INSERT INTO app_settings(clinic_id,key,value_json,updated_at) VALUES(?,?,?,?) ON CONFLICT(clinic_id,key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at`,clinicId,String(row.key),String(row.value_json),String(row.updated_at));
        this.synchronizeCounters(clinicId);
        if(filesToCopy.length)fs.mkdirSync(fileRollbackDirectory,{recursive:true,mode:0o700});
        for(const [index,file] of filesToCopy.entries()){fs.mkdirSync(path.dirname(file.to),{recursive:true,mode:0o700});const temporary=`${file.to}.restore-${randomUUID()}.tmp`;fs.copyFileSync(file.from,temporary);try{if(fs.existsSync(file.to)){const backup=path.join(fileRollbackDirectory,`${index}.previous`);fs.renameSync(file.to,backup);replacedFiles.push({backup,target:file.to});}fs.renameSync(temporary,file.to);copiedFiles.push(file.to);}catch(error){fs.rmSync(temporary,{force:true});throw error;}}
      });
      fs.rmSync(fileRollbackDirectory,{recursive:true,force:true});return{imported,skipped};
    }catch(error){for(const file of copiedFiles)fs.rmSync(file,{force:true});for(const replaced of [...replacedFiles].reverse()){try{fs.mkdirSync(path.dirname(replaced.target),{recursive:true,mode:0o700});if(fs.existsSync(replaced.backup))fs.renameSync(replaced.backup,replaced.target);}catch(rollbackError){this.logger.error('Could not restore an attachment after selective restore rollback',rollbackError);}}fs.rmSync(fileRollbackDirectory,{recursive:true,force:true});throw error;}
    finally{source.close();}
  }

  private synchronizeCounters(clinicId:string):void{
    const sequences=[['patient','patients','patient_code'],['appointment','appointments','appointment_code'],['visit','visits','visit_number'],['prescription','prescriptions','prescription_number'],['treatment_plan','treatment_plans','plan_number'],['referral','referrals','referral_number'],['invoice','invoices','invoice_number'],['receipt','payments','receipt_number'],['expense','expenses','expense_number'],['staff','staff','staff_code']] as const;
    for(const [key,table,column] of sequences){const row=this.db.get<{maximum:number|null}>(`SELECT max(CASE WHEN ${column} GLOB '*[0-9][0-9][0-9][0-9][0-9][0-9]' THEN CAST(substr(${column},-6) AS INTEGER) ELSE 0 END) AS maximum FROM ${table} WHERE clinic_id=?`,clinicId);this.db.run(`INSERT INTO counters(clinic_id,counter_key,current_value) VALUES(?,?,?) ON CONFLICT(clinic_id,counter_key) DO UPDATE SET current_value=max(counters.current_value,excluded.current_value)`,clinicId,key,Number(row?.maximum??0));}
  }

  private chooseTarget(sourceId:string,existingId:string|undefined,strategy:RestoreSelection['duplicateStrategy']):{id:string;skip:boolean;update:boolean;copy:boolean}{
    if(!existingId)return{id:sourceId,skip:false,update:false,copy:false};if(strategy==='skip')return{id:existingId,skip:true,update:false,copy:false};if(strategy==='update')return{id:existingId,skip:false,update:true,copy:false};return{id:randomUUID(),skip:false,update:false,copy:true};
  }

  private uniqueCode(table:string,column:string,base:string):string{for(let i=1;i<10000;i++){const code=`${base}-R${i}`;if(!this.db.get(`SELECT 1 AS found FROM ${table} WHERE ${column}=? COLLATE NOCASE`,code))return code;}throw new AppError('RESTORE_CODE_CONFLICT','A unique record number could not be generated during restore.');}

  private insertRaw(table:string,row:Record<string,unknown>,update=false,ignore=false):void{
    const columns=Object.keys(row);const values=columns.map((column)=>{const value=row[column];return value===undefined?null:value as string|number|bigint|Buffer|null;});const quoted=columns.map((column)=>`"${column.replaceAll('"','""')}"`).join(',');let sql=`INSERT ${ignore?'OR IGNORE ':''}INTO "${table}"(${quoted}) VALUES(${columns.map(()=>'?').join(',')})`;
    if(update){const assignments=columns.filter((c)=>c!=='id').map((c)=>`"${c}"=excluded."${c}"`).join(',');sql+=` ON CONFLICT(id) DO UPDATE SET ${assignments}`;}this.db.run(sql,...values);
  }

  private counts(database:DentivaDatabase|DatabaseSync,clinicId:string|undefined):Record<string,number>{
    const tables=['patients','visits','clinical_notes','dental_chart_entries','prescriptions','treatment_catalog','treatment_plans','treatment_plan_items','referrals','appointments','invoices','payments','refunds','expenses','staff','staff_salary_history','inventory_items','attachments'];const direct=new Set(['patients','visits','prescriptions','treatment_catalog','treatment_plans','referrals','appointments','invoices','payments','refunds','expenses','staff','inventory_items','attachments']);const result:Record<string,number>={};
    for(const table of tables){try{let sql=`SELECT count(*) AS n FROM ${table}`;const params:string[]=[];if(clinicId){if(direct.has(table)){sql+=' WHERE clinic_id=?';params.push(clinicId);}else if(table==='clinical_notes'){sql='SELECT count(*) AS n FROM clinical_notes n JOIN visits v ON v.id=n.visit_id WHERE v.clinic_id=?';params.push(clinicId);}else if(table==='dental_chart_entries'){sql='SELECT count(*) AS n FROM dental_chart_entries d JOIN patients p ON p.id=d.patient_id WHERE p.clinic_id=?';params.push(clinicId);}else if(table==='staff_salary_history'){sql='SELECT count(*) AS n FROM staff_salary_history h JOIN staff s ON s.id=h.staff_id WHERE s.clinic_id=?';params.push(clinicId);}else if(table==='treatment_plan_items'){sql='SELECT count(*) AS n FROM treatment_plan_items i JOIN treatment_plans p ON p.id=i.plan_id WHERE p.clinic_id=?';params.push(clinicId);}}let row:Record<string,unknown>|undefined;if(database instanceof DatabaseSync)row=database.prepare(sql).get(...params) as Record<string,unknown>;else row=database.get<Record<string,unknown>>(sql,...params);result[table]=Number(row?.n??0);}catch{result[table]=0;}}
    return result;
  }

  private async writeArchive(destination:string,manifestPath:string,snapshot:string,files:ManifestFile[]):Promise<void>{
    await new Promise<void>((resolve,reject)=>{const output=fs.createWriteStream(destination,{mode:0o600});const zip=archiver('zip',{zlib:{level:6}});output.on('close',resolve);output.on('error',reject);zip.on('warning',(error)=>error.code==='ENOENT'?this.logger.warn('Backup archive warning',error):reject(error));zip.on('error',reject);zip.pipe(output);zip.file(manifestPath,{name:'manifest.json'});zip.file(snapshot,{name:'database/dentiva.db'});for(const file of files){if(file.category==='attachment')zip.file(this.paths.resolveAttachment(file.path.slice('attachments/'.length)),{name:file.path});else if(file.category==='branding')zip.file(path.join(this.paths.branding,path.basename(file.path)),{name:file.path});}void zip.finalize();});
  }

  private async encryptFile(source:string,destination:string,password:string):Promise<void>{
    const salt=randomBytes(16);const iv=randomBytes(12);const key=pbkdf2Sync(password,salt,ENCRYPTION_ITERATIONS,32,'sha512');const cipher=createCipheriv('aes-256-gcm',key,iv);fs.writeFileSync(destination,Buffer.concat([ENCRYPTION_MARKER,salt,iv]),{mode:0o600});await pipeline(fs.createReadStream(source),cipher,fs.createWriteStream(destination,{flags:'a'}));fs.appendFileSync(destination,cipher.getAuthTag());
  }

  private async decryptFile(source:string,destination:string,password?:string):Promise<boolean>{
    const handle=fs.openSync(source,'r');const marker=Buffer.alloc(ENCRYPTION_MARKER.length);fs.readSync(handle,marker,0,marker.length,0);fs.closeSync(handle);if(!marker.equals(ENCRYPTION_MARKER)){fs.copyFileSync(source,destination);return false;}if(!password)throw new AppError('BACKUP_PASSWORD_REQUIRED','This backup is encrypted. Enter its backup password.');const size=fs.statSync(source).size;if(size<ENCRYPTION_MARKER.length+16+12+16)throw new AppError('INVALID_BACKUP','The encrypted backup is incomplete.');const header=Buffer.alloc(28);const fd=fs.openSync(source,'r');fs.readSync(fd,header,0,28,ENCRYPTION_MARKER.length);const tag=Buffer.alloc(16);fs.readSync(fd,tag,0,16,size-16);fs.closeSync(fd);const salt=header.subarray(0,16),iv=header.subarray(16,28);const key=pbkdf2Sync(password,salt,ENCRYPTION_ITERATIONS,32,'sha512');const decipher=createDecipheriv('aes-256-gcm',key,iv);decipher.setAuthTag(tag);try{await pipeline(fs.createReadStream(source,{start:ENCRYPTION_MARKER.length+28,end:size-17}),decipher,fs.createWriteStream(destination,{mode:0o600}));return true;}catch{fs.rmSync(destination,{force:true});throw new AppError('BACKUP_PASSWORD_INVALID','The backup password is incorrect, or the encrypted package has been altered.');}
  }

  private async extractAndVerify(packagePath:string,password?:string):Promise<ExtractedPackage>{
    const source=path.resolve(packagePath);if(!fs.existsSync(source)||!fs.statSync(source).isFile())throw new AppError('FILE_NOT_FOUND','The selected backup file could not be found.');const directory=path.join(this.paths.temp,`restore-${randomUUID()}`);fs.mkdirSync(directory,{recursive:true,mode:0o700});const archive=path.join(directory,'package.zip');
    try{const encrypted=await this.decryptFile(source,archive,password);await this.extractZip(archive,directory);const manifestPath=path.join(directory,'manifest.json');if(!fs.existsSync(manifestPath))throw new AppError('INVALID_BACKUP','The package manifest is missing.');const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8')) as BackupManifest;if(manifest.format!=='Dentiva Backup'||manifest.packageVersion!==PACKAGE_VERSION||!Array.isArray(manifest.files))throw new AppError('BACKUP_VERSION_INCOMPATIBLE','This file is not a supported Dentiva backup package.');for(const file of manifest.files){const actual=path.resolve(directory,...file.path.split('/'));if(!actual.startsWith(path.resolve(directory)+path.sep)||!fs.existsSync(actual))throw new AppError('BACKUP_INCOMPLETE',`The backup is missing ${path.basename(file.path)}.`);if(fs.statSync(actual).size!==file.size||await sha256File(actual)!==file.sha256)throw new AppError('BACKUP_CHECKSUM_FAILED',`Integrity verification failed for ${path.basename(file.path)}.`);}const databasePath=path.join(directory,'database','dentiva.db');return{directory,manifest,databasePath,encrypted};}
    catch(error){fs.rmSync(directory,{recursive:true,force:true});throw error;}
  }

  private async extractZip(zipPath:string,destination:string):Promise<void>{
    const zip=await new Promise<ZipFile>((resolve,reject)=>yauzl.open(zipPath,{lazyEntries:true,decodeStrings:true,validateEntrySizes:true},(error,file)=>error||!file?reject(error??new Error('Invalid ZIP')):resolve(file)));
    let total=0;const stat=fs.statfsSync(destination);const available=Number(stat.bavail)*Number(stat.bsize);await new Promise<void>((resolve,reject)=>{let settled=false;const fail=(error:unknown)=>{if(settled)return;settled=true;try{zip.close();}catch{}reject(error);};zip.on('error',fail);zip.on('end',()=>{if(!settled){settled=true;resolve();}});zip.on('entry',(entry:Entry)=>{void(async()=>{try{const name=entry.fileName.replaceAll('\\','/');const normalized=path.posix.normalize(name);const unixMode=(entry.externalFileAttributes>>>16)&0o170000;if(!normalized||normalized.startsWith('../')||normalized.startsWith('/')||normalized.includes('\0')||unixMode===0o120000)throw new AppError('UNSAFE_BACKUP','The backup contains an unsafe file path.');total+=entry.uncompressedSize;if(total>available*0.9)throw new AppError('INSUFFICIENT_STORAGE','There is not enough free disk space to inspect this backup.');const target=path.resolve(destination,...normalized.split('/'));if(!target.startsWith(path.resolve(destination)+path.sep))throw new AppError('UNSAFE_BACKUP','The backup contains an unsafe file path.');if(name.endsWith('/'))fs.mkdirSync(target,{recursive:true,mode:0o700});else{fs.mkdirSync(path.dirname(target),{recursive:true,mode:0o700});const stream=await new Promise<NodeJS.ReadableStream>((res,rej)=>zip.openReadStream(entry,(error,value)=>error||!value?rej(error??new Error('Cannot read ZIP entry')):res(value)));await pipeline(stream,fs.createWriteStream(target,{mode:0o600}));}zip.readEntry();}catch(error){fail(error);}})();});zip.readEntry();});
  }
}
