import fs from 'node:fs';
import path from 'node:path';
import archiver from 'archiver';
import type { DateRange } from '../../shared/types.js';
import type { DentivaDatabase } from '../database/database.js';
import type { AuditService } from '../security/security.js';
import type { DentivaPaths } from '../utils/paths.js';
import { AppError } from '../utils/errors.js';
import type { DocumentService } from './document-service.js';

const xml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!)).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'');
const html=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));

interface ExportTable{title:string;headers:string[];rows:unknown[][];currencyColumns:number[];dateColumns:number[]}

export class ExportService{
  constructor(private readonly db:DentivaDatabase,private readonly paths:DentivaPaths,private readonly audit:AuditService,private readonly documents:DocumentService){}

  async export(clinicId:string,userId:string,userName:string,input:{report:string;range:DateRange;format:'csv'|'xlsx'|'pdf';destination?:string}):Promise<{path:string}>{
    const table=this.data(clinicId,input.report,input.range);const stamp=new Date().toISOString().slice(0,10);const base=`Dentiva-${input.report.replace(/[^A-Za-z0-9]+/g,'-')}-${stamp}`;let target=input.destination?path.resolve(input.destination):path.join(this.paths.exports,`${base}.${input.format}`);
    if(fs.existsSync(target)&&fs.statSync(target).isDirectory())target=path.join(target,`${base}.${input.format}`);if(path.extname(target).toLowerCase()!==`.${input.format}`)target+=`.${input.format}`;fs.mkdirSync(path.dirname(target),{recursive:true});
    if(input.format==='csv')this.csv(table,target);else if(input.format==='xlsx')await this.xlsx(table,target);else await this.pdf(table,target,input.range);
    this.audit.record({clinicId,userId,userName,action:'data_exported',entityType:'report',entityIdentifier:input.report,summary:`${table.title} exported as ${input.format.toUpperCase()}`});return{path:target};
  }

  private data(clinicId:string,report:string,range:DateRange):ExportTable{
    const from=range.from.slice(0,10),to=range.to.slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)throw new AppError('VALIDATION_ERROR','Select a valid export date range.');
    switch(report){
      case'patients':{const rows=this.db.all<Record<string,unknown>>(`SELECT patient_code,full_name,phone,email,gender,date_of_birth,registration_date,last_visit,next_appointment,outstanding_minor,status FROM patients WHERE clinic_id=? AND registration_date BETWEEN ? AND ? ORDER BY registration_date,patient_code`,clinicId,from,to);return{title:'Patient report',headers:['Patient code','Full name','Phone','Email','Gender','Date of birth','Registration date','Last visit','Next appointment','Outstanding','Status'],rows:rows.map((r)=>[r.patient_code,r.full_name,r.phone,r.email as string|null,r.gender,r.date_of_birth as string|null,r.registration_date,r.last_visit as string|null,r.next_appointment as string|null,Number(r.outstanding_minor)/100,r.status]),currencyColumns:[9],dateColumns:[5,6,7,8]};}
      case'appointments':{const rows=this.db.all<Record<string,unknown>>(`SELECT a.appointment_code,p.patient_code,p.full_name,a.start_at,a.duration_minutes,a.appointment_type,a.reason,a.serial_number,a.status,s.name AS dentist FROM appointments a JOIN patients p ON p.id=a.patient_id LEFT JOIN staff s ON s.id=a.dentist_id WHERE a.clinic_id=? AND substr(a.start_at,1,10) BETWEEN ? AND ? ORDER BY a.start_at`,clinicId,from,to);return{title:'Appointment report',headers:['Appointment','Patient code','Patient','Date and time','Minutes','Type','Reason','Serial','Status','Dentist'],rows:rows.map((r)=>[r.appointment_code,r.patient_code,r.full_name,r.start_at,Number(r.duration_minutes),r.appointment_type,r.reason as string|null,r.serial_number as number|null,r.status,r.dentist as string|null]),currencyColumns:[],dateColumns:[3]};}
      case'visits':{const rows=this.db.all<Record<string,unknown>>(`SELECT v.visit_number,p.patient_code,p.full_name,v.visited_at,v.chief_complaint,v.diagnosis,v.treatment_performed,v.next_visit_date,v.status,s.name AS provider FROM visits v JOIN patients p ON p.id=v.patient_id LEFT JOIN staff s ON s.id=v.provider_id WHERE v.clinic_id=? AND substr(v.visited_at,1,10) BETWEEN ? AND ? ORDER BY v.visited_at`,clinicId,from,to);return{title:'Clinical activity report',headers:['Visit','Patient code','Patient','Visited at','Chief complaint','Diagnosis','Treatment performed','Next visit','Status','Provider'],rows:rows.map((r)=>[r.visit_number,r.patient_code,r.full_name,r.visited_at,r.chief_complaint as string|null,r.diagnosis as string|null,r.treatment_performed as string|null,r.next_visit_date as string|null,r.status,r.provider as string|null]),currencyColumns:[],dateColumns:[3,7]};}
      case'invoices':{const rows=this.db.all<Record<string,unknown>>(`SELECT i.invoice_number,p.patient_code,p.full_name,i.issued_at,i.subtotal_minor,i.discount_minor,i.tax_minor,i.total_minor,i.paid_minor,i.due_minor,i.status FROM invoices i JOIN patients p ON p.id=i.patient_id WHERE i.clinic_id=? AND substr(i.issued_at,1,10) BETWEEN ? AND ? ORDER BY i.issued_at`,clinicId,from,to);return{title:'Invoice and receivable report',headers:['Invoice','Patient code','Patient','Issued','Subtotal','Discount','Tax','Total','Paid','Due','Status'],rows:rows.map((r)=>[r.invoice_number,r.patient_code,r.full_name,r.issued_at,Number(r.subtotal_minor)/100,Number(r.discount_minor)/100,Number(r.tax_minor)/100,Number(r.total_minor)/100,Number(r.paid_minor)/100,Number(r.due_minor)/100,r.status]),currencyColumns:[4,5,6,7,8,9],dateColumns:[3]};}
      case'payments':{const rows=this.db.all<Record<string,unknown>>(`SELECT pay.receipt_number,i.invoice_number,p.patient_code,p.full_name,pay.paid_at,pay.amount_minor,pay.method,pay.provider,pay.reference FROM payments pay JOIN invoices i ON i.id=pay.invoice_id JOIN patients p ON p.id=i.patient_id WHERE pay.clinic_id=? AND substr(pay.paid_at,1,10) BETWEEN ? AND ? AND pay.voided_at IS NULL ORDER BY pay.paid_at`,clinicId,from,to);return{title:'Payment report',headers:['Receipt','Invoice','Patient code','Patient','Paid at','Amount','Method','Provider','Reference'],rows:rows.map((r)=>[r.receipt_number,r.invoice_number,r.patient_code,r.full_name,r.paid_at,Number(r.amount_minor)/100,r.method,r.provider as string|null,r.reference as string|null]),currencyColumns:[5],dateColumns:[4]};}
      case'expenses':{const rows=this.db.all<Record<string,unknown>>(`SELECT e.expense_number,c.name AS category,e.expense_date,e.amount_minor,e.payee,e.method,e.reference,e.description,e.status FROM expenses e JOIN expense_categories c ON c.id=e.category_id WHERE e.clinic_id=? AND e.expense_date BETWEEN ? AND ? ORDER BY e.expense_date`,clinicId,from,to);return{title:'Expense report',headers:['Expense','Category','Date','Amount','Payee','Method','Reference','Description','Status'],rows:rows.map((r)=>[r.expense_number,r.category,r.expense_date,Number(r.amount_minor)/100,r.payee as string|null,r.method,r.reference as string|null,r.description,r.status]),currencyColumns:[3],dateColumns:[2]};}
      case'inventory':{const rows=this.db.all<Record<string,unknown>>(`SELECT i.sku,i.name,c.name AS category,i.unit,i.current_stock,i.minimum_stock,i.purchase_price_minor,s.name AS supplier,i.expiry_date,i.batch_number,i.location,i.active FROM inventory_items i LEFT JOIN inventory_categories c ON c.id=i.category_id LEFT JOIN suppliers s ON s.id=i.supplier_id WHERE i.clinic_id=? ORDER BY i.name`,clinicId);return{title:'Inventory report',headers:['SKU','Item','Category','Unit','Current stock','Minimum stock','Purchase price','Supplier','Expiry','Batch','Location','Active'],rows:rows.map((r)=>[r.sku,r.name,r.category as string|null,r.unit,Number(r.current_stock),Number(r.minimum_stock),Number(r.purchase_price_minor)/100,r.supplier as string|null,r.expiry_date as string|null,r.batch_number as string|null,r.location as string|null,Number(r.active)===1?'Yes':'No']),currencyColumns:[6],dateColumns:[8]};}
      default:throw new AppError('REPORT_NOT_FOUND','Select a supported report to export.');
    }
  }

  private csv(table:ExportTable,target:string):void{const cell=(v:unknown)=>{const raw=v===null?'':String(v);const text=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return`"${text.replaceAll('"','""')}"`;};const lines=[table.headers.map(cell).join(','),...table.rows.map((row)=>row.map(cell).join(','))];fs.writeFileSync(target,`\uFEFF${lines.join('\r\n')}\r\n`,{encoding:'utf8',mode:0o600});}

  private async xlsx(table:ExportTable,target:string):Promise<void>{
    const column=(n:number)=>{let s='';for(let x=n+1;x;x=Math.floor((x-1)/26))s=String.fromCharCode(65+(x-1)%26)+s;return s;};
    const rowXml=(row:unknown[],index:number,header=false)=>`<row r="${index}">${row.map((value,col)=>{const ref=`${column(col)}${index}`;if(typeof value==='number')return`<c r="${ref}"${table.currencyColumns.includes(col)?' s="2"':''}><v>${value}</v></c>`;return`<c r="${ref}" t="inlineStr"${header?' s="1"':''}><is><t xml:space="preserve">${xml(value)}</t></is></c>`;}).join('')}</row>`;
    const sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${table.headers.map((h,i)=>`<col min="${i+1}" max="${i+1}" width="${Math.min(45,Math.max(12,h.length+4))}" customWidth="1"/>`).join('')}</cols><sheetData>${rowXml(table.headers,1,true)}${table.rows.map((r,i)=>rowXml(r,i+2)).join('')}</sheetData><autoFilter ref="A1:${column(table.headers.length-1)}${table.rows.length+1}"/></worksheet>`;
    const content=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`;
    const rels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;
    const workbook=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${xml(table.title.slice(0,31))}" sheetId="1" r:id="rId1"/></sheets></workbook>`;
    const workbookRels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
    const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Aptos"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Aptos"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF173F79"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/><xf numFmtId="4" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs></styleSheet>`;
    await new Promise<void>((resolve,reject)=>{const output=fs.createWriteStream(target,{mode:0o600});const zip=archiver('zip',{zlib:{level:6}});output.on('close',resolve);output.on('error',reject);zip.on('error',reject);zip.pipe(output);zip.append(content,{name:'[Content_Types].xml'});zip.append(rels,{name:'_rels/.rels'});zip.append(workbook,{name:'xl/workbook.xml'});zip.append(workbookRels,{name:'xl/_rels/workbook.xml.rels'});zip.append(styles,{name:'xl/styles.xml'});zip.append(sheet,{name:'xl/worksheets/sheet1.xml'});void zip.finalize();});
  }

  private async pdf(table:ExportTable,target:string,range:DateRange):Promise<void>{const body=`<header style="display:flex;justify-content:space-between;border-bottom:2px solid #173f79;padding-bottom:14px"><div><h1 style="margin:0;color:#173f79">Dentiva</h1><p>Professional clinic report</p></div><div style="text-align:right"><h2>${html(table.title)}</h2><p>${html(range.from.slice(0,10))} — ${html(range.to.slice(0,10))}</p></div></header><table><thead><tr>${table.headers.map((h)=>`<th>${html(h)}</th>`).join('')}</tr></thead><tbody>${table.rows.map((r)=>`<tr>${r.map((v)=>`<td>${html(v)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${table.headers.length}">No records in the selected date range.</td></tr>`}</tbody></table><footer style="margin-top:24px;color:#677586">Generated by Dentiva · ${html(new Date().toISOString())}</footer>`;await this.documents.htmlToPdf(body,path.basename(target,'.pdf'),target);}
}
