import { randomUUID } from 'node:crypto';
import type { RoleDefinition, RoleInput, UserAccount, UserAccountInput } from '../../shared/types.js';
import type { DentivaDatabase } from '../database/database.js';
import { hashPassword } from '../security/security.js';
import type { AuditService } from '../security/security.js';
import { AppError, assertText, optionalText } from '../utils/errors.js';

export class UserService {
  constructor(private readonly db:DentivaDatabase,private readonly audit:AuditService){}

  list(clinicId:string):UserAccount[]{
    const users=this.db.all<Record<string,unknown>>('SELECT id,username,display_name,language,status,failed_login_count,locked_until,last_login_at,password_changed_at,created_at FROM users WHERE clinic_id=? ORDER BY status,display_name',clinicId);
    return users.map((row)=>this.mapUser(row));
  }

  roles(clinicId:string):{roles:RoleDefinition[];permissions:Array<{code:string;name:string;description:string}>}{
    const rows=this.db.all<Record<string,unknown>>(`SELECT r.*,count(DISTINCT ur.user_id) AS user_count FROM roles r LEFT JOIN user_roles ur ON ur.role_id=r.id WHERE r.clinic_id=? GROUP BY r.id ORDER BY r.is_system DESC,r.name`,clinicId);
    return{roles:rows.map((row)=>this.mapRole(row)),permissions:this.db.all<{code:string;name:string;description:string}>('SELECT code,name,description FROM permissions ORDER BY code')};
  }

  create(clinicId:string,actorId:string,actorName:string,input:UserAccountInput):UserAccount{
    const id=randomUUID();const username=this.username(input.username);const displayName=assertText(input.displayName,'Display name',2,180);if(!input.password)throw new AppError('VALIDATION_ERROR','Enter a temporary password for the new account.','password');const password=hashPassword(input.password);const roles=this.validRoles(clinicId,input.roleIds);const now=new Date().toISOString();
    try{this.db.transaction(()=>{this.db.run(`INSERT INTO users(id,clinic_id,username,display_name,password_hash,password_salt,password_iterations,language,status,failed_login_count,locked_until,last_login_at,password_changed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,0,NULL,NULL,?,?,?)`,id,clinicId,username,displayName,password.hash,password.salt,password.iterations,input.language==='bn'?'bn':'en',input.status==='disabled'?'disabled':'active',now,now,now);for(const role of roles)this.db.run('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',id,role);this.audit.record({clinicId,userId:actorId,userName:actorName,action:'user_created',entityType:'user',entityIdentifier:id,summary:`User account ${username} created`});});}catch(error){if(error instanceof Error&&error.message.includes('UNIQUE'))throw new AppError('DUPLICATE_USERNAME','This username is already used by another account.','username');throw error;}return this.get(clinicId,id);
  }

  update(clinicId:string,actorId:string,actorName:string,id:string,input:Omit<UserAccountInput,'password'>):UserAccount{
    const current=this.db.get<Record<string,unknown>>('SELECT * FROM users WHERE id=? AND clinic_id=?',id,clinicId);if(!current)throw new AppError('NOT_FOUND','User account not found.');if(id===actorId&&input.status==='disabled')throw new AppError('SELF_LOCKOUT','You cannot disable the account currently signed in.');const roles=this.validRoles(clinicId,input.roleIds);this.ensureOwnerRemains(clinicId,id,roles,input.status);
    try{this.db.transaction(()=>{this.db.run(`UPDATE users SET username=?,display_name=?,language=?,status=?,failed_login_count=CASE WHEN ?='active' THEN 0 ELSE failed_login_count END,locked_until=CASE WHEN ?='active' THEN NULL ELSE locked_until END,updated_at=? WHERE id=?`,this.username(input.username),assertText(input.displayName,'Display name',2,180),input.language==='bn'?'bn':'en',input.status==='disabled'?'disabled':'active',input.status,input.status,new Date().toISOString(),id);this.db.run('DELETE FROM user_roles WHERE user_id=?',id);for(const role of roles)this.db.run('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',id,role);this.audit.record({clinicId,userId:actorId,userName:actorName,action:'user_updated',entityType:'user',entityIdentifier:id,summary:`User account ${String(current.username)} updated`});});}catch(error){if(error instanceof Error&&error.message.includes('UNIQUE'))throw new AppError('DUPLICATE_USERNAME','This username is already used by another account.','username');throw error;}return this.get(clinicId,id);
  }

  resetPassword(clinicId:string,actorId:string,actorName:string,id:string,passwordValue:string):void{
    const user=this.db.get<{username:string}>('SELECT username FROM users WHERE id=? AND clinic_id=?',id,clinicId);if(!user)throw new AppError('NOT_FOUND','User account not found.');const password=hashPassword(passwordValue);const now=new Date().toISOString();this.db.run(`UPDATE users SET password_hash=?,password_salt=?,password_iterations=?,password_changed_at=?,failed_login_count=0,locked_until=NULL,status=CASE WHEN status='locked' THEN 'active' ELSE status END,updated_at=? WHERE id=?`,password.hash,password.salt,password.iterations,now,now,id);this.audit.record({clinicId,userId:actorId,userName:actorName,action:'user_password_reset',entityType:'user',entityIdentifier:id,summary:`Password reset for ${user.username}`});
  }

  createRole(clinicId:string,actorId:string,actorName:string,input:RoleInput):RoleDefinition{
    const id=randomUUID();const name=assertText(input.name,'Role name',2,100);const permissions=this.validPermissions(input.permissions);const now=new Date().toISOString();try{this.db.transaction(()=>{this.db.run('INSERT INTO roles(id,clinic_id,name,description,is_system,created_at) VALUES(?,?,?,?,0,?)',id,clinicId,name,optionalText(input.description,500),now);for(const code of permissions)this.db.run('INSERT INTO role_permissions(role_id,permission_code) VALUES(?,?)',id,code);this.audit.record({clinicId,userId:actorId,userName:actorName,action:'role_created',entityType:'role',entityIdentifier:id,summary:`Access role ${name} created`});});}catch(error){if(error instanceof Error&&error.message.includes('UNIQUE'))throw new AppError('DUPLICATE_ROLE','A role with this name already exists.','name');throw error;}return this.getRole(clinicId,id);
  }

  updateRole(clinicId:string,actorId:string,actorName:string,id:string,input:RoleInput):RoleDefinition{
    const role=this.db.get<{name:string;is_system:number}>('SELECT name,is_system FROM roles WHERE id=? AND clinic_id=?',id,clinicId);if(!role)throw new AppError('NOT_FOUND','Access role not found.');if(role.is_system)throw new AppError('SYSTEM_ROLE_PROTECTED','Built-in roles are protected. Create a custom role for different permissions.');const name=assertText(input.name,'Role name',2,100);const permissions=this.validPermissions(input.permissions);this.db.transaction(()=>{this.db.run('UPDATE roles SET name=?,description=? WHERE id=?',name,optionalText(input.description,500),id);this.db.run('DELETE FROM role_permissions WHERE role_id=?',id);for(const code of permissions)this.db.run('INSERT INTO role_permissions(role_id,permission_code) VALUES(?,?)',id,code);this.audit.record({clinicId,userId:actorId,userName:actorName,action:'role_updated',entityType:'role',entityIdentifier:id,summary:`Access role ${name} updated`});});return this.getRole(clinicId,id);
  }

  deleteRole(clinicId:string,actorId:string,actorName:string,id:string):void{
    const role=this.db.get<{name:string;is_system:number}>('SELECT name,is_system FROM roles WHERE id=? AND clinic_id=?',id,clinicId);if(!role)throw new AppError('NOT_FOUND','Access role not found.');if(role.is_system)throw new AppError('SYSTEM_ROLE_PROTECTED','Built-in roles cannot be deleted.');if(this.db.get<{n:number}>('SELECT count(*) AS n FROM user_roles WHERE role_id=?',id)!.n>0)throw new AppError('ROLE_IN_USE','Remove this role from all user accounts before deleting it.');this.db.run('DELETE FROM roles WHERE id=?',id);this.audit.record({clinicId,userId:actorId,userName:actorName,action:'role_deleted',entityType:'role',entityIdentifier:id,summary:`Access role ${role.name} deleted`});
  }

  private get(clinicId:string,id:string):UserAccount{const row=this.db.get<Record<string,unknown>>('SELECT id,username,display_name,language,status,failed_login_count,locked_until,last_login_at,password_changed_at,created_at FROM users WHERE id=? AND clinic_id=?',id,clinicId);if(!row)throw new AppError('NOT_FOUND','User account not found.');return this.mapUser(row);}
  private mapUser(row:Record<string,unknown>):UserAccount{return{id:String(row.id),username:String(row.username),displayName:String(row.display_name),language:row.language==='bn'?'bn':'en',status:row.status as UserAccount['status'],failedLoginCount:Number(row.failed_login_count),lockedUntil:row.locked_until?String(row.locked_until):null,lastLoginAt:row.last_login_at?String(row.last_login_at):null,passwordChangedAt:String(row.password_changed_at),createdAt:String(row.created_at),roles:this.db.all<{id:string;name:string}>('SELECT r.id,r.name FROM roles r JOIN user_roles ur ON ur.role_id=r.id WHERE ur.user_id=? ORDER BY r.name',String(row.id))};}
  private getRole(clinicId:string,id:string):RoleDefinition{const row=this.db.get<Record<string,unknown>>(`SELECT r.*,count(DISTINCT ur.user_id) AS user_count FROM roles r LEFT JOIN user_roles ur ON ur.role_id=r.id WHERE r.id=? AND r.clinic_id=? GROUP BY r.id`,id,clinicId);if(!row)throw new AppError('NOT_FOUND','Access role not found.');return this.mapRole(row);}
  private mapRole(row:Record<string,unknown>):RoleDefinition{return{id:String(row.id),name:String(row.name),description:row.description?String(row.description):null,isSystem:Boolean(row.is_system),permissions:this.db.all<{permission_code:string}>('SELECT permission_code FROM role_permissions WHERE role_id=? ORDER BY permission_code',String(row.id)).map((item)=>item.permission_code),userCount:Number(row.user_count??0)};}
  private username(value:unknown):string{const username=assertText(value,'Username',2,80).toLowerCase();if(!/^[a-z0-9][a-z0-9._-]*$/.test(username))throw new AppError('VALIDATION_ERROR','Use letters, numbers, dots, underscores, or hyphens for the username.','username');return username;}
  private validRoles(clinicId:string,values:string[]):string[]{const ids=[...new Set(Array.isArray(values)?values:[])];if(!ids.length)throw new AppError('VALIDATION_ERROR','Assign at least one access role.','roleIds');for(const id of ids)if(!this.db.get('SELECT id FROM roles WHERE id=? AND clinic_id=?',id,clinicId))throw new AppError('VALIDATION_ERROR','One of the selected roles is not available.','roleIds');return ids;}
  private validPermissions(values:string[]):string[]{const codes=[...new Set(Array.isArray(values)?values:[])];for(const code of codes)if(!this.db.get('SELECT code FROM permissions WHERE code=?',code))throw new AppError('VALIDATION_ERROR',`Unknown permission: ${code}`,'permissions');return codes;}
  private ensureOwnerRemains(clinicId:string,userId:string,nextRoles:string[],status:'active'|'disabled'):void{const owner=this.db.get<{id:string}>("SELECT id FROM roles WHERE clinic_id=? AND name='Owner / Administrator' COLLATE NOCASE",clinicId);if(!owner)return;const currentlyOwner=Boolean(this.db.get('SELECT 1 AS found FROM user_roles WHERE user_id=? AND role_id=?',userId,owner.id));if(!currentlyOwner||(status==='active'&&nextRoles.includes(owner.id)))return;const other=this.db.get<{n:number}>(`SELECT count(DISTINCT u.id) AS n FROM users u JOIN user_roles ur ON ur.user_id=u.id WHERE u.clinic_id=? AND u.id!=? AND u.status='active' AND ur.role_id=?`,clinicId,userId,owner.id);if(!other?.n)throw new AppError('OWNER_REQUIRED','The clinic must retain at least one active Owner account.');}
}
