import fs from 'node:fs';
import path from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { AttachmentService } from '../../src/main/services/attachment-service.js';
import { BackupService } from '../../src/main/services/backup-service.js';
import { BillingService } from '../../src/main/services/billing-service.js';
import { PatientService } from '../../src/main/services/patient-service.js';
import { TreatmentPlanService } from '../../src/main/services/treatment-plan-service.js';
import type { PatientInput } from '../../src/shared/types.js';
import { createWorkspace, setupInput, type TestWorkspace } from '../helpers.js';

const person:PatientInput={fullName:'Sharmin Akter',preferredName:null,phone:'01713000003',alternativePhone:null,email:null,dateOfBirth:'1988-02-10',gender:'female',bloodGroup:null,address:'Dhaka',emergencyContact:null,emergencyPhone:null,occupation:null,identificationType:null,identificationNumber:null,medicalAlerts:null,allergiesSummary:null,currentMedications:null,medicalConditions:null,dentalHistory:null,previousDentist:null,referralSource:null,status:'active',notes:null,tags:[],isFavorite:false};

describe('verified backup and selective restore',()=>{
  const workspaces:TestWorkspace[]=[];afterEach(()=>{for(const workspace of workspaces)workspace.dispose();workspaces.length=0;});
  it('creates, encrypts, verifies, analyses, and selectively restores a Dentiva package',async()=>{
    const source=createWorkspace();workspaces.push(source);const sourceSession=source.setup.complete(setupInput('S'));const sourceClinic=source.setup.bootstrap().clinic!.id;
    const patients=new PatientService(source.db,source.audit);const patient=patients.create(sourceClinic,sourceSession.user.id,sourceSession.user.displayName,person);
    const billing=new BillingService(source.db,source.audit);const invoice=billing.create(sourceClinic,sourceSession.user.id,sourceSession.user.displayName,{patientId:patient.id,visitId:null,issuedAt:'2026-09-21',dueAt:null,discountMinor:0,notes:null,terms:null,issueNow:true,items:[{treatmentId:null,description:'Authorised clinic service',quantity:1,unitPriceMinor:7500,discountMinor:0,taxRate:0}]});billing.addPayment(sourceClinic,sourceSession.user.id,sourceSession.user.displayName,{invoiceId:invoice.id,amountMinor:2500,paidAt:'2026-09-21T12:00',method:'Cash'});
    new TreatmentPlanService(source.db,source.audit).create(sourceClinic,sourceSession.user.id,sourceSession.user.displayName,{patientId:patient.id,title:'Reviewed care plan',items:[{description:'Confirmed plan item',quantity:1,unitFeeMinor:9000,discountMinor:0,status:'planned'}]});
    const original=path.join(source.root,'radiograph.pdf');fs.writeFileSync(original,'%PDF-1.4\n% secure attachment test\n');const attachments=new AttachmentService(source.db,source.paths,source.audit);await attachments.add(sourceClinic,sourceSession.user.id,sourceSession.user.displayName,{sourcePath:original,patientId:patient.id,category:'xray',description:'Clinical image document'});
    const sourceBackup=new BackupService(source.db,source.paths,source.audit,source.logger,'1.0.0');const password='Backup#Secure2026';const record=await sourceBackup.create(sourceClinic,sourceSession.user.id,sourceSession.user.displayName,{destination:source.paths.backups,encryptPassword:password,type:'manual'});
    expect(record.status).toBe('verified');expect(fs.existsSync(record.filePath)).toBe(true);expect((await sourceBackup.verifyFile(record.filePath,password)).valid).toBe(true);expect((await sourceBackup.verifyFile(record.filePath,'Incorrect#Password')).valid).toBe(false);
    const analysis=await sourceBackup.analyze(record.filePath,password);expect(analysis.counts.patients).toBe(1);expect(analysis.counts.attachments).toBe(1);expect(analysis.counts.treatment_plans).toBe(1);expect(analysis.patients[0]?.patientCode).toBe('DTV-000001');

    const blocked=createWorkspace();workspaces.push(blocked);const blockedSession=blocked.setup.complete(setupInput('R'));const blockedClinic=blocked.setup.bootstrap().clinic!.id;fs.writeFileSync(path.join(blocked.paths.attachments,patient.id),'blocks the required patient attachment directory');const blockedBackup=new BackupService(blocked.db,blocked.paths,blocked.audit,blocked.logger,'1.0.0');await expect(blockedBackup.restore(blockedClinic,blockedSession.user.id,blockedSession.user.displayName,record.filePath,{modules:['patients','treatment_plans','invoices','payments','attachments'],patientIds:[patient.id],duplicateStrategy:'skip',password})).rejects.toThrow();expect(blocked.db.get<{n:number}>('SELECT count(*) AS n FROM patients WHERE clinic_id=?',blockedClinic)?.n).toBe(0);expect(blocked.db.get<{status:string}>('SELECT status FROM import_jobs ORDER BY started_at DESC LIMIT 1')?.status).toBe('rolled_back');

    const target=createWorkspace();workspaces.push(target);const targetSession=target.setup.complete(setupInput('T'));const targetClinic=target.setup.bootstrap().clinic!.id;const targetBackup=new BackupService(target.db,target.paths,target.audit,target.logger,'1.0.0');
    await expect(targetBackup.restore(targetClinic,targetSession.user.id,targetSession.user.displayName,record.filePath,{modules:['all'],duplicateStrategy:'skip',password})).rejects.toMatchObject({code:'BACKUP_CLINIC_MISMATCH'});expect(target.db.get<{n:number}>('SELECT count(*) AS n FROM patients WHERE clinic_id=?',targetClinic)?.n).toBe(0);
    const result=await targetBackup.restore(targetClinic,targetSession.user.id,targetSession.user.displayName,record.filePath,{modules:['patients','treatment_plans','invoices','payments','attachments'],patientIds:[patient.id],duplicateStrategy:'skip',password});
    expect(result.imported.patients).toBe(1);expect(result.imported.invoices).toBe(1);expect(result.imported.treatmentPlans).toBe(1);expect(result.imported.payments).toBe(1);expect(result.imported.attachments).toBe(1);
    const restored=target.db.get<{id:string;outstanding_minor:number}>('SELECT id,outstanding_minor FROM patients WHERE clinic_id=? AND patient_code=?',targetClinic,patient.patientCode)!;expect(restored).toBeTruthy();expect(restored.outstanding_minor).toBe(5000);
    const restoredAttachment=target.db.get<{relative_path:string}>('SELECT relative_path FROM attachments WHERE patient_id=?',restored.id)!;expect(fs.existsSync(target.paths.resolveAttachment(restoredAttachment.relative_path))).toBe(true);expect(target.db.integrityCheck()).toBe('ok');expect(target.db.foreignKeyCheck()).toEqual([]);
    const repeated=await targetBackup.restore(targetClinic,targetSession.user.id,targetSession.user.displayName,record.filePath,{modules:['patients','treatment_plans','invoices','payments','attachments'],patientIds:[patient.id],duplicateStrategy:'skip',password});expect(repeated.skipped.patients).toBe(1);expect(target.db.get<{n:number}>('SELECT count(*) AS n FROM patients WHERE clinic_id=?',targetClinic)?.n).toBe(1);
  },120000);

  it('fully replaces the same clinic workspace and preserves a completed restore audit trail',async()=>{
    const workspace=createWorkspace();workspaces.push(workspace);const session=workspace.setup.complete(setupInput('F'));const clinicId=workspace.setup.bootstrap().clinic!.id;const patients=new PatientService(workspace.db,workspace.audit);const first=patients.create(clinicId,session.user.id,session.user.displayName,{...person,phone:'01714000004'});
    const sourceFile=path.join(workspace.root,'clinical-document.pdf');fs.writeFileSync(sourceFile,'%PDF-1.4\noriginal managed bytes\n');const attachmentService=new AttachmentService(workspace.db,workspace.paths,workspace.audit);const attachment=await attachmentService.add(clinicId,session.user.id,session.user.displayName,{sourcePath:sourceFile,patientId:first.id,category:'document'});const managed=workspace.paths.resolveAttachment(attachment.relativePath);
    const backup=new BackupService(workspace.db,workspace.paths,workspace.audit,workspace.logger,'1.0.0');const record=await backup.create(clinicId,session.user.id,session.user.displayName,{type:'manual'});patients.create(clinicId,session.user.id,session.user.displayName,{...person,fullName:'Second Record',phone:'01714000005'});fs.writeFileSync(managed,'changed after backup');
    const integrityFailure=vi.spyOn(workspace.db,'integrityCheck').mockReturnValueOnce('injected failure');await expect(backup.restore(clinicId,session.user.id,session.user.displayName,record.filePath,{modules:['all'],duplicateStrategy:'skip'})).rejects.toThrow('The restored database did not pass integrity validation.');integrityFailure.mockRestore();expect(workspace.db.get<{n:number}>('SELECT count(*) AS n FROM patients WHERE clinic_id=?',clinicId)?.n).toBe(2);expect(fs.readFileSync(managed,'utf8')).toBe('changed after backup');expect(workspace.db.get<{status:string}>('SELECT status FROM import_jobs WHERE mode=\'full\' ORDER BY started_at DESC LIMIT 1')?.status).toBe('rolled_back');
    const result=await backup.restore(clinicId,session.user.id,session.user.displayName,record.filePath,{modules:['all'],duplicateStrategy:'skip'});expect(result.imported.all).toBeGreaterThan(0);expect(workspace.db.get<{n:number}>('SELECT count(*) AS n FROM patients WHERE clinic_id=?',clinicId)?.n).toBe(1);expect(fs.readFileSync(managed,'utf8')).toContain('original managed bytes');expect(workspace.db.get<{status:string}>('SELECT status FROM import_jobs WHERE mode=\'full\' ORDER BY completed_at DESC LIMIT 1')?.status).toBe('completed');expect(workspace.db.get<{n:number}>('SELECT count(*) AS n FROM audit_logs WHERE action=\'backup_restored\' AND outcome=\'success\'',)?.n).toBe(1);expect(workspace.db.integrityCheck()).toBe('ok');expect(workspace.db.foreignKeyCheck()).toEqual([]);
  },120000);
});
