import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
vi.mock('electron',()=>({BrowserWindow:class{}}));
import { DocumentService } from '../../src/main/services/document-service.js';
import { BillingService } from '../../src/main/services/billing-service.js';
import { PatientService } from '../../src/main/services/patient-service.js';
import { RecordsService } from '../../src/main/services/records-service.js';
import { SettingsService } from '../../src/main/services/settings-service.js';
import type { DocumentRequest, PatientInput } from '../../src/shared/types.js';
import { createWorkspace, setupInput, type TestWorkspace } from '../helpers.js';

type RenderResult={html:string;title:string;fileName:string;paper:'A4'|'A5'|'58mm'|'80mm'};
type Renderable={render(clinicId:string,request:DocumentRequest,toolbar:boolean):RenderResult};

describe('bilingual branded document rendering',()=>{let workspace:TestWorkspace;let service:DocumentService;let clinicId:string;let userId:string;let patientId:string;let invoiceId:string;let paymentId:string;let referralId:string;beforeEach(()=>{workspace=createWorkspace();const session=workspace.setup.complete(setupInput('D'));clinicId=workspace.setup.bootstrap().clinic!.id;userId=session.user.id;service=new DocumentService(workspace.db,workspace.paths,workspace.audit,()=>null);const patient:PatientInput={fullName:'Amina <script>alert(1)</script>',preferredName:null,phone:'01716000007',alternativePhone:null,email:null,dateOfBirth:null,gender:'female',bloodGroup:null,address:'Dhaka',emergencyContact:null,emergencyPhone:null,occupation:null,identificationType:null,identificationNumber:null,medicalAlerts:'Clinician-recorded alert',allergiesSummary:'Recorded allergies',currentMedications:'Recorded medicines',medicalConditions:null,dentalHistory:null,previousDentist:null,referralSource:null,status:'active',notes:null,tags:[],isFavorite:false};patientId=new PatientService(workspace.db,workspace.audit).create(clinicId,userId,'Clinic Owner',patient).id;const billing=new BillingService(workspace.db,workspace.audit);const invoice=billing.create(clinicId,userId,'Clinic Owner',{patientId,visitId:null,issuedAt:'2026-09-21',dueAt:null,discountMinor:0,notes:'Document note',terms:'Clinic terms',issueNow:true,items:[{treatmentId:null,description:'Approved service',quantity:1,unitPriceMinor:10000,discountMinor:0,taxRate:0}]});invoiceId=invoice.id;paymentId=billing.addPayment(clinicId,userId,'Clinic Owner',{invoiceId,amountMinor:5000,paidAt:'2026-09-21T12:00',method:'Cash'}).id;referralId=String((new RecordsService(workspace.db,workspace.audit).create(clinicId,userId,'Clinic Owner','referrals',{patientId,reason:'Clinician-confirmed referral reason',destination:'Specialist department',provider:'Receiving clinician',referralDate:'2026-09-21'}) as {id:unknown}).id);});afterEach(()=>workspace.dispose());
  const render=(request:DocumentRequest,toolbar=false)=>((service as unknown as Renderable).render(clinicId,request,toolbar));
  it('escapes record content and emits Bengali patient summaries with bundled print styling',()=>{const result=render({type:'patient_summary',entityId:patientId,language:'bn',paperSize:'A5'},true);expect(result.paper).toBe('A5');expect(result.html).toContain('<html lang="bn">');expect(result.html).toContain('চিকিৎসা সতর্কতা');expect(result.html).toContain('প্রিন্ট করুন');expect(result.html).toContain('Amina &lt;script&gt;alert(1)&lt;/script&gt;');expect(result.html).not.toContain('<script>alert(1)</script>');expect(result.html).toContain('@font-face');});
  it('renders invoices, money receipts, and clinician-confirmed referral letters',()=>{const invoice=render({type:'invoice',entityId:invoiceId,language:'en',paperSize:'A4'});expect(invoice.html).toContain('INV-2026-000001');expect(invoice.html).toContain('৳100.00');const referral=render({type:'referral',entityId:referralId,language:'bn',paperSize:'A4'});expect(referral.title).toBe('রেফারেল পত্র');expect(referral.html).toContain('রেফারেলের কারণ');expect(referral.html).toContain('Specialist department');});
  it('honours the configurable receipt paper width when no size is requested',()=>{new SettingsService(workspace.db,workspace.audit,workspace.paths).updateApp(clinicId,userId,'Clinic Owner',{receiptWidth:'58mm'});const receipt=render({type:'receipt',entityId:paymentId,language:'en'});expect(receipt.paper).toBe('58mm');expect(receipt.html).toContain('@page{size:58mm auto');});
});
