import fs from 'node:fs';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { SettingsService } from '../../src/main/services/settings-service.js';
import { InsightsService } from '../../src/main/services/insights-service.js';
import { createWorkspace, setupInput, type TestWorkspace } from '../helpers.js';

describe('clinic customization settings',()=>{let workspace:TestWorkspace;let service:SettingsService;let clinicId:string;let userId:string;beforeEach(()=>{workspace=createWorkspace();const session=workspace.setup.complete(setupInput('C'));clinicId=workspace.setup.bootstrap().clinic!.id;userId=session.user.id;service=new SettingsService(workspace.db,workspace.audit,workspace.paths);});afterEach(()=>workspace.dispose());
  it('updates regional, numbering, document and application preferences',()=>{const clinic=service.updateClinic(clinicId,userId,'Clinic Owner',{country:'Bangladesh',currencyCode:'BDT',currencySymbol:'৳',patientPrefix:'PT',appointmentPrefix:'BOOK',invoicePrefix:'BILL',workingDays:['Saturday','Sunday'],footerText:'Clinic-approved document footer',paymentInstructions:'Accepted payment instructions'});expect(clinic.patientPrefix).toBe('PT');expect(clinic.workingDays).toEqual(['Saturday','Sunday']);const app=service.updateApp(clinicId,userId,'Clinic Owner',{receiptWidth:'58mm',autoLockMinutes:5,defaultAppointmentMinutes:45,language:'bn'});expect(app.receiptWidth).toBe('58mm');expect(app.autoLockMinutes).toBe(5);expect(service.updatePaymentMethods(clinicId,userId,'Clinic Owner',['Cash','bKash','Cash','Clinic credit'])).toEqual(['Cash','bKash','Clinic credit']);expect(()=>service.updatePaymentMethods(clinicId,userId,'Clinic Owner',[])).toThrow(/at least one/);expect(()=>service.updateApp(clinicId,userId,'Clinic Owner',{autoLockMinutes:0})).toThrow(/between 1 and 240/);const insights=new InsightsService(workspace.db);insights.generateOperationalNotifications(clinicId);expect(insights.notifications(clinicId).some((item)=>item.type==='backup_reminder')).toBe(true);service.updateApp(clinicId,userId,'Clinic Owner',{notificationsEnabled:false});expect(insights.notifications(clinicId)).toEqual([]);});
  it('copies logos into managed branding storage and supports safe removal',()=>{const source=path.join(workspace.root,'clinic-logo.png');fs.writeFileSync(source,Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]));const clinic=service.updateLogo(clinicId,userId,'Clinic Owner',source);expect(clinic.logoPath).toContain('clinic-logo-');expect(fs.existsSync(clinic.logoPath!)).toBe(true);expect(path.dirname(clinic.logoPath!)).toBe(workspace.paths.branding);expect(service.updateLogo(clinicId,userId,'Clinic Owner',null).logoPath).toBeNull();expect(fs.existsSync(clinic.logoPath!)).toBe(false);const invalid=path.join(workspace.root,'logo.svg');fs.writeFileSync(invalid,'<svg/>');expect(()=>service.updateLogo(clinicId,userId,'Clinic Owner',invalid)).toThrow(/PNG, JPG, or WEBP/);});
});
