import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { UserService } from '../../src/main/services/user-service.js';
import { createWorkspace, setupInput, type TestWorkspace } from '../helpers.js';

describe('user and role administration',()=>{
  let workspace:TestWorkspace;let service:UserService;let ownerId:string;let clinicId:string;
  beforeEach(()=>{workspace=createWorkspace();const owner=workspace.setup.complete(setupInput('U'));ownerId=owner.user.id;clinicId=workspace.setup.bootstrap().clinic!.id;service=new UserService(workspace.db,workspace.audit);});afterEach(()=>workspace.dispose());
  it('creates custom least-privilege roles and securely managed accounts',()=>{const role=service.createRole(clinicId,ownerId,'Clinic Owner',{name:'Front Desk Limited',description:'Appointment and patient registration access',permissions:['patients.view','patients.edit','appointments.view','appointments.edit']});expect(role.isSystem).toBe(false);expect(role.permissions).toHaveLength(4);const account=service.create(clinicId,ownerId,'Clinic Owner',{username:'reception.one',displayName:'Reception One',password:'Reception#Secure2026',language:'bn',status:'active',roleIds:[role.id]});expect(account.roles[0]?.name).toBe('Front Desk Limited');const restrictedSession=workspace.sessions.login({username:'reception.one',password:'Reception#Secure2026'});expect(restrictedSession.user.permissions).toContain('appointments.edit');service.updateRole(clinicId,ownerId,'Clinic Owner',role.id,{name:'Front Desk Limited',description:'Patient registration only',permissions:['patients.view','patients.edit']});expect(()=>workspace.sessions.require(restrictedSession.token,'appointments.edit')).toThrow(/permission/i);service.resetPassword(clinicId,ownerId,'Clinic Owner',account.id,'Changed#Secure2026');expect(()=>workspace.sessions.require(restrictedSession.token)).toThrow(/credentials changed/i);expect(()=>workspace.sessions.login({username:'reception.one',password:'Reception#Secure2026'})).toThrow();const changedSession=workspace.sessions.login({username:'reception.one',password:'Changed#Secure2026'});expect(changedSession.user.language).toBe('bn');service.update(clinicId,ownerId,'Clinic Owner',account.id,{username:account.username,displayName:account.displayName,language:'bn',status:'disabled',roleIds:[role.id]});expect(()=>workspace.sessions.require(changedSession.token)).toThrow(/account or credentials changed/i);});
  it('prevents self-lockout, owner loss, and mutation of protected built-in roles',()=>{const owner=service.list(clinicId).find((item)=>item.id===ownerId)!;expect(()=>service.update(clinicId,ownerId,'Clinic Owner',owner.id,{username:owner.username,displayName:owner.displayName,language:'en',status:'disabled',roleIds:owner.roles.map((role)=>role.id)})).toThrow(/cannot disable/i);const ownerRole=service.roles(clinicId).roles.find((role)=>role.name==='Owner / Administrator')!;expect(()=>service.updateRole(clinicId,ownerId,'Clinic Owner',ownerRole.id,{name:'Changed Owner',permissions:[]})).toThrow(/protected/i);expect(()=>service.deleteRole(clinicId,ownerId,'Clinic Owner',ownerRole.id)).toThrow(/cannot be deleted/i);});
  it('audits account and role lifecycle changes',()=>{const role=service.createRole(clinicId,ownerId,'Clinic Owner',{name:'Reports Reviewer',permissions:['reports.view']});service.updateRole(clinicId,ownerId,'Clinic Owner',role.id,{name:'Reports Auditor',description:'Read-only reports',permissions:['reports.view','audit.view']});service.deleteRole(clinicId,ownerId,'Clinic Owner',role.id);const actions=workspace.db.all<{action:string}>('SELECT action FROM audit_logs WHERE clinic_id=?',clinicId).map((row)=>row.action);expect(actions).toEqual(expect.arrayContaining(['role_created','role_updated','role_deleted']));expect(()=>workspace.db.run("UPDATE audit_logs SET summary='changed' WHERE clinic_id=?",clinicId)).toThrow(/immutable/i);expect(()=>workspace.db.run('DELETE FROM audit_logs WHERE clinic_id=?',clinicId)).toThrow(/immutable/i);});
  it('locks an account after repeated unsuccessful sign-in attempts',()=>{for(let attempt=0;attempt<4;attempt+=1)expect(()=>workspace.sessions.login({username:'owner.u',password:'Wrong#Password2026'})).toThrow(/incorrect/i);expect(()=>workspace.sessions.login({username:'owner.u',password:'Wrong#Password2026'})).toThrow(/locked/i);expect(()=>workspace.sessions.login({username:'owner.u',password:'Secure#Clinic2026'})).toThrow(/locked/i);expect(workspace.db.get<{status:string;failed_login_count:number}>('SELECT status,failed_login_count FROM users WHERE id=?',ownerId)).toMatchObject({status:'locked',failed_login_count:5});workspace.db.run("UPDATE users SET locked_until='2020-01-01T00:00:00.000Z' WHERE id=?",ownerId);expect(workspace.sessions.login({username:'owner.u',password:'Secure#Clinic2026'}).user.id).toBe(ownerId);expect(workspace.db.get<{status:string;failed_login_count:number}>('SELECT status,failed_login_count FROM users WHERE id=?',ownerId)).toMatchObject({status:'active',failed_login_count:0});});
});
