import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { PatientService } from '../../src/main/services/patient-service.js';
import { AppointmentService } from '../../src/main/services/appointment-service.js';
import { ClinicalService } from '../../src/main/services/clinical-service.js';
import { BillingService } from '../../src/main/services/billing-service.js';
import { RecordsService } from '../../src/main/services/records-service.js';
import { TreatmentPlanService } from '../../src/main/services/treatment-plan-service.js';
import { InsightsService } from '../../src/main/services/insights-service.js';
import type { PatientInput, Session } from '../../src/shared/types.js';
import { createWorkspace, setupInput, type TestWorkspace } from '../helpers.js';

const patientInput:PatientInput={fullName:'Rahim Uddin',preferredName:'Rahim',phone:'01711000001',alternativePhone:null,email:'rahim@patient.local',dateOfBirth:'1990-06-15',gender:'male',bloodGroup:'B+',address:'Dhanmondi, Dhaka',emergencyContact:'Family Contact',emergencyPhone:'01811000001',occupation:'Teacher',identificationType:null,identificationNumber:null,medicalAlerts:'Requires clinician review before treatment',allergiesSummary:'Recorded allergy information',currentMedications:null,medicalConditions:null,dentalHistory:null,previousDentist:null,referralSource:'Clinic referral',status:'active',notes:null,tags:['priority'],isFavorite:false};

describe('critical clinic workflows',()=>{
  let workspace:TestWorkspace;let session:Session;let patients:PatientService;let appointments:AppointmentService;let clinical:ClinicalService;let billing:BillingService;let records:RecordsService;let plans:TreatmentPlanService;let insights:InsightsService;
  beforeEach(()=>{workspace=createWorkspace();session=workspace.setup.complete(setupInput());patients=new PatientService(workspace.db,workspace.audit);appointments=new AppointmentService(workspace.db,workspace.audit);clinical=new ClinicalService(workspace.db,workspace.audit);billing=new BillingService(workspace.db,workspace.audit);records=new RecordsService(workspace.db,workspace.audit);plans=new TreatmentPlanService(workspace.db,workspace.audit);insights=new InsightsService(workspace.db);});
  afterEach(()=>workspace.dispose());

  it('initializes an empty production database and authenticates securely',()=>{
    expect(workspace.db.schemaVersion).toBe(4);expect(workspace.db.integrityCheck()).toBe('ok');expect(workspace.db.foreignKeyCheck()).toEqual([]);
    expect(workspace.db.get<{n:number}>('SELECT count(*) AS n FROM patients')?.n).toBe(0);expect(workspace.db.get<{n:number}>('SELECT count(*) AS n FROM invoices')?.n).toBe(0);
    const loggedIn=workspace.sessions.login({username:'owner.a',password:'Secure#Clinic2026'});expect(loggedIn.user.permissions).toContain('backup.restore');expect(()=>workspace.sessions.login({username:'owner.a',password:'incorrect'})).toThrow();
  });

  it('creates, edits, finds, archives, and restores a patient without losing history',()=>{
    const created=patients.create(session.user.id?workspace.setup.bootstrap().clinic!.id:'',session.user.id,session.user.displayName,patientInput);
    expect(created.patientCode).toBe('DTV-000001');expect(created.age).toBeGreaterThan(30);
    const search=patients.list(created.clinicId,{page:1,pageSize:25,search:'Rahim 01711'});expect(search.total).toBe(1);
    const updated=patients.update(created.id,created.clinicId,session.user.id,session.user.displayName,{preferredName:'R. Uddin'});expect(updated.preferredName).toBe('R. Uddin');
    patients.archive(created.id,created.clinicId,session.user.id,session.user.displayName);expect(patients.list(created.clinicId,{page:1,pageSize:25}).total).toBe(0);
    patients.restore(created.id,created.clinicId,session.user.id,session.user.displayName);expect(patients.get(created.id,created.clinicId).status).toBe('active');
  });

  it('enforces appointment conflicts and maintains a daily serial queue',()=>{
    const clinicId=workspace.setup.bootstrap().clinic!.id;const patient=patients.create(clinicId,session.user.id,session.user.displayName,patientInput);
    const staff=records.create(clinicId,session.user.id,session.user.displayName,'staff',{name:'Dr. Nusrat Karim',role:'Dentist',phone:'01712000002',status:'active',salaryMinor:6000000,salaryFrequency:'Monthly',joiningDate:'2026-01-01'}) as {id:string};
    records.update(clinicId,session.user.id,session.user.displayName,'staff',staff.id,{salaryMinor:6500000,salaryFrequency:'Monthly',salaryEffectiveFrom:'2026-07-01',salaryChangeNotes:'Approved salary revision'});const salaryHistory=records.list(clinicId,{entity:'staff',page:1,pageSize:100,filters:{lookup:'salaryHistory',staffId:staff.id}});expect(salaryHistory.items).toHaveLength(2);expect(salaryHistory.items[0]?.amountMinor).toBe(6500000);
    const first=appointments.create(clinicId,session.user.id,session.user.displayName,{patientId:patient.id,dentistId:staff.id,appointmentType:'Consultation',reason:'Dental evaluation',startAt:'2030-05-10T10:00',durationMinutes:30,status:'scheduled',notes:null,followUp:false,chair:'Chair 1'});
    expect(first.serialNumber).toBe(1);expect(()=>appointments.create(clinicId,session.user.id,session.user.displayName,{patientId:patient.id,dentistId:staff.id,appointmentType:'Follow-up',reason:null,startAt:'2030-05-10T10:15',durationMinutes:30,status:'scheduled',notes:null,followUp:true,chair:'Chair 1'})).toThrow(/overlaps/);
    expect(appointments.day(clinicId,'2030-05-10')).toHaveLength(1);expect(appointments.setStatus(first.id,clinicId,session.user.id,session.user.displayName,'waiting').status).toBe('waiting');
  });

  it('records immutable clinical chronology, dental charting, and prescriptions',()=>{
    const clinicId=workspace.setup.bootstrap().clinic!.id;const patient=patients.create(clinicId,session.user.id,session.user.displayName,patientInput);
    const visit=clinical.createVisit(clinicId,session.user.id,session.user.displayName,{patientId:patient.id,appointmentId:null,providerId:null,visitedAt:'2026-09-21T10:00',chiefComplaint:'Patient-reported dental discomfort',reason:null,symptoms:null,clinicalFindings:'Clinical findings entered by dentist',diagnosis:'Dentist-confirmed diagnosis',treatmentPlan:'Documented treatment plan',treatmentPerformed:null,procedureDetails:null,materialsUsed:null,followUpRecommendation:'Review after seven days',nextVisitDate:'2026-09-28',dentistNotes:null,assistantNotes:null,status:'open'});
    const note=clinical.addNote(visit.id,clinicId,session.user.id,session.user.displayName,{noteType:'progress',content:'Progress note entered by authorised clinician.'});expect(note.content).toContain('authorised');
    const chart=clinical.setChartEntry(clinicId,session.user.id,session.user.displayName,{patientId:patient.id,visitId:visit.id,dentition:'adult',toothNumber:'11',surface:'labial',condition:'Clinical observation',procedure:null,status:'observed',notes:null});expect(chart.toothNumber).toBe('11');
    const prescription=clinical.createPrescription(clinicId,session.user.id,session.user.displayName,{patientId:patient.id,visitId:visit.id,prescribedAt:'2026-09-21T10:30',providerId:'',diagnosis:'Dentist-confirmed diagnosis',advice:'Instructions confirmed by prescriber',followUpDate:'2026-09-28',language:'en',items:[{medicineName:'Clinician-entered medicine',genericName:null,strength:'500 mg',dosage:'1 tablet',frequency:'Twice daily',duration:'5 days',route:'Oral',mealTiming:'After meal',quantity:'10',instructions:'Follow prescriber instructions',notes:null}]});
    expect(prescription.items).toHaveLength(1);let treatmentPlan=plans.create(clinicId,session.user.id,session.user.displayName,{patientId:patient.id,visitId:visit.id,providerId:null,title:'Clinician-reviewed phased treatment',notes:'Estimate reviewed with patient',items:[{description:'Clinician-selected procedure',toothNumber:'11',quantity:1,unitFeeMinor:120000,discountMinor:5000,status:'planned'}]});expect(treatmentPlan.planNumber).toMatch(/^TPL-2026-/);expect(treatmentPlan.totalEstimateMinor).toBe(115000);for(const nextStatus of ['presented','accepted','in_progress','completed'] as const)treatmentPlan=plans.update(treatmentPlan.id,clinicId,session.user.id,session.user.displayName,{patientId:patient.id,visitId:visit.id,providerId:null,title:treatmentPlan.title,status:nextStatus,notes:treatmentPlan.notes,items:treatmentPlan.items.map((item)=>({id:item.id,treatmentId:item.treatmentId,toothNumber:item.toothNumber,description:item.description,quantity:item.quantity,unitFeeMinor:item.unitFeeMinor,discountMinor:item.discountMinor,status:nextStatus==='completed'?'completed':item.status,notes:item.notes}))});expect(treatmentPlan.status).toBe('completed');expect(()=>plans.update(treatmentPlan.id,clinicId,session.user.id,session.user.displayName,{patientId:patient.id,title:treatmentPlan.title,status:'draft',items:[]})).toThrow(/read-only/);const referral=records.create(clinicId,session.user.id,session.user.displayName,'referrals',{patientId:patient.id,visitId:visit.id,reason:'Clinician-confirmed coordinated care requirement',destination:'Specialist department',provider:'Receiving clinician',referralDate:'2026-09-21',notes:'Referral reviewed with patient'}) as unknown as {id:string;referralNumber:string;status:string};expect(referral.referralNumber).toMatch(/^REF-2026-/);const completedReferral=records.update(clinicId,session.user.id,session.user.displayName,'referrals',referral.id,{status:'completed',response:'Response received and recorded',outcome:'Follow-up arranged'}) as unknown as {status:string};expect(completedReferral.status).toBe('completed');expect(clinical.completeVisit(visit.id,clinicId,session.user.id,session.user.displayName).status).toBe('completed');expect(patients.get(patient.id,clinicId).visits).toHaveLength(1);const restrictedProfile=patients.get(patient.id,clinicId,['patients.view']);expect(restrictedProfile.visits).toEqual([]);expect(restrictedProfile.chart).toEqual([]);expect(restrictedProfile.prescriptions).toEqual([]);
  });

  it('reconciles invoice totals, partial/full payments, and refunds transactionally',()=>{
    const clinicId=workspace.setup.bootstrap().clinic!.id;const patient=patients.create(clinicId,session.user.id,session.user.displayName,patientInput);
    const invoice=billing.create(clinicId,session.user.id,session.user.displayName,{patientId:patient.id,visitId:null,issuedAt:'2026-09-21',dueAt:'2026-09-30',discountMinor:500,notes:null,terms:null,issueNow:true,items:[{treatmentId:null,description:'Clinic service entered by authorised user',quantity:2,unitPriceMinor:5000,discountMinor:1000,taxRate:5}]});
    expect(invoice.subtotalMinor).toBe(9000);expect(invoice.taxMinor).toBe(450);expect(invoice.totalMinor).toBe(8950);expect(invoice.dueMinor).toBe(8950);
    const first=billing.addPayment(clinicId,session.user.id,session.user.displayName,{invoiceId:invoice.id,amountMinor:3000,paidAt:'2026-09-21T11:00',method:'Cash'});expect(billing.get(invoice.id,clinicId).status).toBe('partially_paid');
    const second=billing.addPayment(clinicId,session.user.id,session.user.displayName,{invoiceId:invoice.id,amountMinor:5950,paidAt:'2026-09-21T11:05',method:'bKash',reference:'TX-100'});expect(billing.get(invoice.id,clinicId).status).toBe('paid');
    billing.refund(clinicId,session.user.id,session.user.displayName,{paymentId:second.id,amountMinor:950,reason:'Approved payment correction'});const reconciled=billing.get(invoice.id,clinicId);expect(reconciled.paidMinor).toBe(8000);expect(reconciled.dueMinor).toBe(950);expect(reconciled.status).toBe('partially_paid');
    const view=workspace.db.get<{payment_total_minor:number;refund_total_minor:number}>('SELECT payment_total_minor,refund_total_minor FROM invoice_reconciliation WHERE invoice_id=?',invoice.id)!;expect(view.payment_total_minor-view.refund_total_minor).toBe(reconciled.paidMinor);expect(first.receiptNumber).toMatch(/^RCT-/);const limitedSearch=insights.globalSearch(clinicId,'Rahim',['patients.view']);expect(new Set(limitedSearch.map((item)=>item.type))).toEqual(new Set(['patient']));expect(insights.globalSearch(clinicId,'Rahim',['patients.view','billing.view']).some((item)=>item.type==='invoice')).toBe(true);
  });

  it('records expenses, inventory movements, dashboard and financial reports',()=>{
    const clinicId=workspace.setup.bootstrap().clinic!.id;const category=workspace.db.get<{id:string}>('SELECT id FROM expense_categories WHERE clinic_id=? ORDER BY sort_order LIMIT 1',clinicId)!;
    records.create(clinicId,session.user.id,session.user.displayName,'expenses',{categoryId:category.id,amountMinor:150000,expenseDate:'2026-09-21',method:'Bank',description:'Monthly operating expense'});
    const item=records.create(clinicId,session.user.id,session.user.displayName,'inventory',{sku:'MAT-001',name:'Clinic material',categoryName:'Consumables',unit:'box',currentStock:10,minimumStock:3,purchasePriceMinor:25000}) as unknown as {id:string;currentStock:number};
    const changed=records.update(clinicId,session.user.id,session.user.displayName,'inventory',item.id,{operation:'transaction',transactionType:'stock_out',quantity:4,notes:'Used in clinic operations'}) as unknown as {currentStock:number};expect(changed.currentStock).toBe(6);
    const treatment=records.create(clinicId,session.user.id,session.user.displayName,'treatments',{code:'SRV-001',name:'Clinician-approved clinic service',category:'General services',defaultFeeMinor:50000,durationMinutes:30,taxRate:0,description:'Catalog description confirmed by clinic'}) as unknown as {id:string;active:boolean};expect(treatment.active).toBe(true);const treatmentUpdated=records.update(clinicId,session.user.id,session.user.displayName,'treatments',treatment.id,{active:false,taxRate:5}) as unknown as {active:boolean;taxRate:number};expect(treatmentUpdated.active).toBe(false);expect(treatmentUpdated.taxRate).toBe(5);const report=insights.report(clinicId,{from:'2026-09-01',to:'2026-09-30'});expect(report.expensesMinor).toBe(150000);expect(report.expenseCategories[0]?.count).toBe(1);expect(workspace.db.foreignKeyCheck()).toEqual([]);
  });
});
