import{useCallback,useEffect,useState}from'react';
import{CheckCircle2,ClipboardPlus,FileText,Plus,Printer,RefreshCw,Search,ShieldCheck,Stethoscope,Trash2}from'lucide-react';
import{useTranslation}from'react-i18next';
import type{PrescriptionItem,Visit,VisitInput}from'../../shared/types';
import{useApp}from'../context/AppContext';
import{PatientPicker}from'../components/PatientPicker';
import{ReferralsPanel}from'../components/ReferralsPanel';
import{TreatmentPlansPanel}from'../components/TreatmentPlansPanel';
import{Badge,Button,Card,DateText,EmptyState,FormField,IconButton,LoadingState,Modal,PageHeader,Pagination,statusTone}from'../components/UI';
function nowInput(){const d=new Date();const p=(n:number)=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;}

export function Clinical(){const{t}=useTranslation();const{session,navOptions,run,notify}=useApp();const[items,setItems]=useState<Visit[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const[page,setPage]=useState(1);const[total,setTotal]=useState(0);const[pages,setPages]=useState(1);const[visitOpen,setVisitOpen]=useState(false);const[rxOpen,setRxOpen]=useState(false);
  const load=useCallback(async()=>{if(!session)return;setLoading(true);try{const data=await run(()=>window.dentiva.clinical.visits(session.token,{page,pageSize:25,search,sortBy:'visitedAt',sortDirection:'desc'}));setItems(data.items);setTotal(data.total);setPages(data.totalPages);}catch{}finally{setLoading(false);}},[session,page,search,run]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),search?250:0);return()=>window.clearTimeout(timer);},[load,search]);useEffect(()=>{if(navOptions.action==='new')setVisitOpen(true);if(navOptions.action==='prescription')setRxOpen(true);},[navOptions]);
  const complete=async(visit:Visit)=>{if(!session)return;try{await run(()=>window.dentiva.clinical.completeVisit(session.token,visit.id));notify('success',t('common.success'));await load();}catch{}};
  return<div className="page"><PageHeader title={t('clinical.title')}subtitle={t('clinical.subtitle')}actions={<><Button variant="secondary"icon={FileText}onClick={()=>setRxOpen(true)}>{t('clinical.newPrescription')}</Button><Button icon={ClipboardPlus}onClick={()=>setVisitOpen(true)}>{t('clinical.start')}</Button></>}/><div className="safety-banner"><ShieldCheck/><span>{t('clinical.safety')}</span></div><Card className="table-card"><div className="table-toolbar"><div className="search-box"><Search/><input value={search}onChange={(e)=>{setSearch(e.target.value);setPage(1);}}placeholder={t('patients.search')}/></div><IconButton label={t('common.refresh')}icon={RefreshCw}onClick={load}/></div>{loading?<LoadingState/>:items.length===0?<EmptyState icon={Stethoscope}title={t('clinical.emptyTitle')}body={t('clinical.emptyBody')}action={<Button icon={ClipboardPlus}onClick={()=>setVisitOpen(true)}>{t('clinical.start')}</Button>}/>:<><div className="data-table-wrap"><table className="data-table"><thead><tr><th>{t('clinical.visitNumber')}</th><th>{t('appointments.patient')}</th><th>{t('common.date')}</th><th>{t('clinical.chiefComplaint')}</th><th>{t('clinical.diagnosis')}</th><th>{t('clinical.provider')}</th><th>{t('common.status')}</th><th>{t('common.actions')}</th></tr></thead><tbody>{items.map((visit)=><tr key={visit.id}><td className="code-cell">{visit.visitNumber}</td><td><b>{visit.patientName}</b><small className="table-sub">{visit.patientCode}</small></td><td><DateText value={visit.visitedAt}withTime/></td><td className="truncate-cell"title={visit.chiefComplaint??''}>{visit.chiefComplaint||'—'}</td><td className="truncate-cell"title={visit.diagnosis??''}>{visit.diagnosis||'—'}</td><td>{visit.providerName||'—'}</td><td><Badge tone={statusTone(visit.status)}>{t(`clinical.${visit.status}`)}</Badge></td><td><div className="row-actions"><IconButton label={t('common.preview')}icon={Printer}onClick={()=>void window.dentiva.documents.preview(session!.token,{type:'visit_summary',entityId:visit.id})}/>{visit.status==='open'&&<IconButton label={t('clinical.completeVisit')}icon={CheckCircle2}onClick={()=>void complete(visit)}/>}</div></td></tr>)}</tbody></table></div><Pagination page={page}totalPages={pages}total={total}onChange={setPage}/></>}</Card><TreatmentPlansPanel/><ReferralsPanel/><VisitForm open={visitOpen}presetPatientId={navOptions.patientId}appointmentId={navOptions.recordId}onClose={()=>setVisitOpen(false)}onSaved={()=>{setVisitOpen(false);notify('success',t('common.success'));void load();}}/><PrescriptionForm open={rxOpen}presetPatientId={navOptions.patientId}onClose={()=>setRxOpen(false)}onSaved={()=>{setRxOpen(false);notify('success',t('common.success'));void load();}}/></div>;
}
function VisitForm({open,presetPatientId,appointmentId,onClose,onSaved}:{open:boolean;presetPatientId?:string;appointmentId?:string;onClose:()=>void;onSaved:()=>void}){const{t}=useTranslation();const{session,run}=useApp();const[patient,setPatient]=useState<{id:string;label:string}|null>(null);const[staff,setStaff]=useState<Array<Record<string,unknown>>>([]);const[provider,setProvider]=useState('');const[busy,setBusy]=useState(false);const[data,setData]=useState<Omit<VisitInput,'patientId'|'providerId'|'appointmentId'>>({visitedAt:nowInput(),chiefComplaint:null,reason:null,symptoms:null,clinicalFindings:null,diagnosis:null,treatmentPlan:null,treatmentPerformed:null,procedureDetails:null,materialsUsed:null,followUpRecommendation:null,nextVisitDate:null,dentistNotes:null,assistantNotes:null,status:'open'});
  useEffect(()=>{if(!open||!session)return;setData({visitedAt:nowInput(),chiefComplaint:null,reason:null,symptoms:null,clinicalFindings:null,diagnosis:null,treatmentPlan:null,treatmentPerformed:null,procedureDetails:null,materialsUsed:null,followUpRecommendation:null,nextVisitDate:null,dentistNotes:null,assistantNotes:null,status:'open'});setPatient(null);setProvider('');void window.dentiva.records.list(session.token,{entity:'staff',page:1,pageSize:100,filters:{lookup:'providers'}}).then((r)=>{if(r.ok)setStaff(r.data?.items??[]);});if(presetPatientId)void window.dentiva.patients.get(session.token,presetPatientId).then((r)=>{if(r.ok&&r.data)setPatient({id:r.data.id,label:`${r.data.fullName} · ${r.data.patientCode}`});});},[open,session,presetPatientId]);const set=(key:keyof typeof data,value:unknown)=>setData((v)=>({...v,[key]:value||null}));
  const save=async()=>{if(!session||!patient)return;setBusy(true);try{await run(()=>window.dentiva.clinical.createVisit(session.token,{...data,patientId:patient.id,providerId:provider||null,appointmentId:appointmentId||null}));onSaved();}catch{}finally{setBusy(false);}};
  return<Modal open={open}onClose={onClose}title={t('clinical.start')}subtitle={t('clinical.safety')}size="xl"footer={<><Button variant="secondary"onClick={onClose}>{t('common.cancel')}</Button><Button onClick={save}disabled={!patient||busy}>{busy?t('common.saving'):t('clinical.saveVisit')}</Button></>}><div className="form-grid cols-2"><FormField label={t('appointments.patient')}required className="span-2"><PatientPicker value={patient}onChange={setPatient}/></FormField><FormField label={t('common.date')}required><input type="datetime-local"value={data.visitedAt.slice(0,16)}onChange={(e)=>set('visitedAt',e.target.value)}/></FormField><FormField label={t('clinical.provider')}><select value={provider}onChange={(e)=>setProvider(e.target.value)}><option value="">{t('common.none')}</option>{staff.filter((s)=>s.status==='active').map((s)=><option key={String(s.id)}value={String(s.id)}>{String(s.name)} · {String(s.role)}</option>)}</select></FormField><FormField label={t('clinical.chiefComplaint')}required className="span-2"><textarea rows={2}value={data.chiefComplaint??''}onChange={(e)=>set('chiefComplaint',e.target.value)}/></FormField><FormField label={t('clinical.symptoms')}><textarea rows={3}value={data.symptoms??''}onChange={(e)=>set('symptoms',e.target.value)}/></FormField><FormField label={t('clinical.findings')}><textarea rows={3}value={data.clinicalFindings??''}onChange={(e)=>set('clinicalFindings',e.target.value)}/></FormField><FormField label={t('clinical.diagnosis')}><textarea rows={3}value={data.diagnosis??''}onChange={(e)=>set('diagnosis',e.target.value)}/></FormField><FormField label={t('clinical.plan')}><textarea rows={3}value={data.treatmentPlan??''}onChange={(e)=>set('treatmentPlan',e.target.value)}/></FormField><FormField label={t('clinical.performed')}><textarea rows={3}value={data.treatmentPerformed??''}onChange={(e)=>set('treatmentPerformed',e.target.value)}/></FormField><FormField label={t('clinical.procedures')}><textarea rows={3}value={data.procedureDetails??''}onChange={(e)=>set('procedureDetails',e.target.value)}/></FormField><FormField label={t('clinical.materials')}><textarea rows={2}value={data.materialsUsed??''}onChange={(e)=>set('materialsUsed',e.target.value)}/></FormField><FormField label={t('clinical.followUp')}><textarea rows={2}value={data.followUpRecommendation??''}onChange={(e)=>set('followUpRecommendation',e.target.value)}/></FormField><FormField label={t('clinical.nextVisit')}><input type="date"value={data.nextVisitDate??''}onChange={(e)=>set('nextVisitDate',e.target.value)}/></FormField><FormField label={t('clinical.dentistNotes')}><textarea rows={3}value={data.dentistNotes??''}onChange={(e)=>set('dentistNotes',e.target.value)}/></FormField><FormField label={t('clinical.assistantNotes')}><textarea rows={3}value={data.assistantNotes??''}onChange={(e)=>set('assistantNotes',e.target.value)}/></FormField></div></Modal>;
}
function PrescriptionForm({open,presetPatientId,onClose,onSaved}:{open:boolean;presetPatientId?:string;onClose:()=>void;onSaved:()=>void}){const{t}=useTranslation();const{session,language,run}=useApp();const[patient,setPatient]=useState<{id:string;label:string}|null>(null);const[diagnosis,setDiagnosis]=useState('');const[advice,setAdvice]=useState('');const[followUp,setFollowUp]=useState('');const[items,setItems]=useState<PrescriptionItem[]>([{medicineName:'',genericName:null,strength:null,dosage:'',frequency:'',duration:'',route:null,mealTiming:null,quantity:null,instructions:null,notes:null}]);const[busy,setBusy]=useState(false);
  useEffect(()=>{if(!open||!session)return;setDiagnosis('');setAdvice('');setFollowUp('');setItems([{medicineName:'',genericName:null,strength:null,dosage:'',frequency:'',duration:'',route:null,mealTiming:null,quantity:null,instructions:null,notes:null}]);setPatient(null);if(presetPatientId)void window.dentiva.patients.get(session.token,presetPatientId).then((r)=>{if(r.ok&&r.data)setPatient({id:r.data.id,label:`${r.data.fullName} · ${r.data.patientCode}`});});},[open,session,presetPatientId]);
  const setItem=(index:number,key:keyof PrescriptionItem,value:string)=>setItems((rows)=>rows.map((row,i)=>i===index?{...row,[key]:value||null}:row));const add=()=>setItems((rows)=>[...rows,{medicineName:'',genericName:null,strength:null,dosage:'',frequency:'',duration:'',route:null,mealTiming:null,quantity:null,instructions:null,notes:null}]);
  const save=async()=>{if(!session||!patient)return;setBusy(true);try{await run(()=>window.dentiva.clinical.createPrescription(session.token,{patientId:patient.id,visitId:null,prescribedAt:new Date().toISOString(),providerId:'',diagnosis:diagnosis||null,advice:advice||null,followUpDate:followUp||null,language,items}));onSaved();}catch{}finally{setBusy(false);}};
  return<Modal open={open}onClose={onClose}title={t('clinical.newPrescription')}subtitle={t('clinical.safety')}size="xl"footer={<><Button variant="secondary"onClick={onClose}>{t('common.cancel')}</Button><Button onClick={save}disabled={!patient||busy}>{busy?t('common.saving'):t('clinical.createPrescription')}</Button></>}><div className="form-grid cols-2"><FormField label={t('appointments.patient')}required className="span-2"><PatientPicker value={patient}onChange={setPatient}/></FormField><FormField label={t('clinical.diagnosis')}><textarea rows={2}value={diagnosis}onChange={(e)=>setDiagnosis(e.target.value)}/></FormField><FormField label={t('clinical.advice')}><textarea rows={2}value={advice}onChange={(e)=>setAdvice(e.target.value)}/></FormField><FormField label={t('clinical.followUp')}><input type="date"value={followUp}onChange={(e)=>setFollowUp(e.target.value)}/></FormField></div><div className="medicine-lines"><header><h3>{t('clinical.medicine')}</h3><Button variant="secondary"size="sm"icon={Plus}onClick={add}>{t('common.add')}</Button></header>{items.map((item,index)=><div className="medicine-row"key={index}><div className="medicine-row-header"><b>{index+1}</b>{items.length>1&&<IconButton label={t('billing.removeLine')}icon={Trash2}onClick={()=>setItems((rows)=>rows.filter((_,i)=>i!==index))}/>}</div><FormField label={t('clinical.medicine')}required><input value={item.medicineName}onChange={(e)=>setItem(index,'medicineName',e.target.value)}/></FormField><FormField label={t('clinical.strength')}><input value={item.strength??''}onChange={(e)=>setItem(index,'strength',e.target.value)}/></FormField><FormField label={t('clinical.dosage')}required><input value={item.dosage}onChange={(e)=>setItem(index,'dosage',e.target.value)}/></FormField><FormField label={t('clinical.frequency')}required><input value={item.frequency}onChange={(e)=>setItem(index,'frequency',e.target.value)}/></FormField><FormField label={t('clinical.duration')}required><input value={item.duration}onChange={(e)=>setItem(index,'duration',e.target.value)}/></FormField><FormField label={t('clinical.mealTiming')}><input value={item.mealTiming??''}onChange={(e)=>setItem(index,'mealTiming',e.target.value)}/></FormField><FormField label={t('clinical.instructions')}className="span-2"><input value={item.instructions??''}onChange={(e)=>setItem(index,'instructions',e.target.value)}/></FormField></div>)}</div></Modal>;
}
