import{useCallback,useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,ArrowRight,CalendarDays,CalendarPlus,ClipboardPlus,Clock3,CreditCard,FilePlus2,Receipt,RefreshCw,Stethoscope,UserPlus,UsersRound,WalletCards}from'lucide-react';
import{useTranslation}from'react-i18next';
import type{DashboardData,DatePreset,DateRange}from'../../shared/types';
import{useApp}from'../context/AppContext';
import{Badge,Button,Card,DateText,EmptyState,ErrorState,LoadingState,Money,PageHeader,statusTone}from'../components/UI';

function localDate(date:Date){const p=(n:number)=>String(n).padStart(2,'0');return`${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}`;}
function rangeFor(preset:DatePreset):DateRange{const to=new Date();const from=new Date(to);if(preset==='7days')from.setDate(from.getDate()-6);else if(preset==='1month')from.setMonth(from.getMonth()-1);else if(preset==='3months')from.setMonth(from.getMonth()-3);else if(preset==='6months')from.setMonth(from.getMonth()-6);else if(preset==='1year')from.setFullYear(from.getFullYear()-1);return{from:localDate(from),to:localDate(to),preset};}

export function Dashboard(){const{t}=useTranslation();const{session,bootstrap,navigate,run}=useApp();const[preset,setPreset]=useState<DatePreset>('today');const[range,setRange]=useState<DateRange>(()=>rangeFor('today'));const[data,setData]=useState<DashboardData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  const load=useCallback(async()=>{if(!session)return;setLoading(true);setError('');try{setData(await run(()=>window.dentiva.dashboard.get(session.token,range)));}catch(err){setError(err instanceof Error?err.message:t('errors.load'));}finally{setLoading(false);}},[session,range,run,t]);useEffect(()=>{void load();},[load]);
  const options=useMemo(()=>[{v:'today',l:t('dashboard.today')},{v:'7days',l:t('dashboard.last7')},{v:'1month',l:t('dashboard.month1')},{v:'3months',l:t('dashboard.month3')},{v:'6months',l:t('dashboard.month6')},{v:'1year',l:t('dashboard.year1')}],[t]);
  const choose=(value:string)=>{const next=value as DatePreset;setPreset(next);setRange(rangeFor(next));};
  return<div className="page"><PageHeader title={t('dashboard.title')}subtitle={t('dashboard.subtitle')}actions={<div className="dashboard-controls"><select value={preset}onChange={(event)=>choose(event.target.value)}aria-label={t('dashboard.timeframe')}>{options.map((option)=><option key={option.v}value={option.v}>{option.l}</option>)}</select><Button variant="quiet"size="sm"icon={RefreshCw}onClick={load}>{t('common.refresh')}</Button></div>}/>{loading?<LoadingState/>:error?<ErrorState message={error}onRetry={load}/>:data&&<>
    <section className="kpi-grid cols-4"><Kpi icon={UsersRound}label={t('dashboard.patients')}value={String(data.patients)}tone="blue"/><Kpi icon={CalendarDays}label={t('dashboard.appointments')}value={String(data.appointments)}tone="teal"/><Kpi icon={Clock3}label={t('dashboard.waiting')}value={String(data.waiting)}tone="amber"/><Kpi icon={Stethoscope}label={t('dashboard.consultations')}value={String(data.completedConsultations)}tone="green"/><Kpi icon={WalletCards}label={t('dashboard.revenue')}value={<Money minor={data.revenueMinor}symbol={bootstrap?.clinic?.currencySymbol}/>}tone="green"/><Kpi icon={CreditCard}label={t('dashboard.outstanding')}value={<Money minor={data.outstandingMinor}symbol={bootstrap?.clinic?.currencySymbol}/>}tone="red"/><Kpi icon={Activity}label={t('dashboard.followups')}value={String(data.followUpsDue)}tone="teal"/><Kpi icon={Receipt}label={t('dashboard.unpaid')}value={String(data.unpaidInvoices)}tone="amber"/></section>
    <section className="dashboard-grid"><Card title={t('dashboard.schedule')}className="schedule-card"action={<button className="text-button"onClick={()=>navigate('appointments')}>{t('common.view')} <ArrowRight size={14}/></button>}>{data.upcomingAppointments.length===0?<EmptyState compact icon={CalendarDays}title={t('dashboard.noAppointments')}body={t('appointments.emptyBody')}/>:<div className="schedule-list">{data.upcomingAppointments.map((item)=><button key={item.id}onClick={()=>navigate('appointments',{recordId:item.id})}><span className="schedule-time"><b>{new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(new Date(item.startAt))}</b><small><DateText value={item.startAt}/></small></span><span className="schedule-person"><b>{item.patientName}</b><small>{item.patientCode} · {item.appointmentType}</small></span>{item.serialNumber&&<span className="serial-chip">{t('dashboard.serial')} {item.serialNumber}</span>}<Badge tone={statusTone(item.status)}>{t(`appointments.${item.status}`)}</Badge></button>)}</div>}</Card>
      <Card title={t('dashboard.quickActions')}className="quick-card"><div className="quick-action-grid"><Quick icon={UserPlus}label={t('topbar.newPatient')}onClick={()=>navigate('patients',{action:'new'})}/><Quick icon={CalendarPlus}label={t('topbar.newAppointment')}onClick={()=>navigate('appointments',{action:'new'})}/><Quick icon={ClipboardPlus}label={t('topbar.newVisit')}onClick={()=>navigate('clinical',{action:'new'})}/><Quick icon={FilePlus2}label={t('topbar.newInvoice')}onClick={()=>navigate('billing',{action:'new'})}/><Quick icon={Receipt}label={t('expenses.new')}onClick={()=>navigate('expenses',{action:'new'})}/><Quick icon={RefreshCw}label={t('backup.create')}onClick={()=>navigate('backup')}/></div></Card>
      <Card title={t('dashboard.recentPatients')}className="recent-card">{data.recentPatients.length===0?<EmptyState compact icon={UsersRound}title={t('dashboard.noRecentPatients')}body={t('patients.emptyBody')}/>:<div className="person-list">{data.recentPatients.map((patient)=><button key={patient.id}onClick={()=>navigate('patients',{patientId:patient.id})}><span className="avatar">{patient.fullName.trim().split(/\s+/).slice(0,2).map((word)=>word[0]).join('').toUpperCase()}</span><span><b>{patient.fullName}</b><small>{patient.patientCode} · {patient.phone}</small></span><ArrowRight size={15}/></button>)}</div>}</Card>
      <Card title={t('dashboard.followUpList')}className="follow-card">{data.followUps.length===0?<EmptyState compact icon={Activity}title={t('dashboard.noFollowups')}body={t('clinical.followUp')}/>:<div className="follow-list">{data.followUps.map((item)=><button key={`${item.patientId}-${item.dueDate}`}onClick={()=>navigate('patients',{patientId:item.patientId})}><span><b>{item.patientName}</b><small>{item.patientCode}</small></span><DateText value={item.dueDate}/></button>)}</div>}</Card>
      <Card title={t('dashboard.clinicalAlerts')}className="alerts-card">{data.lowStock.length===0?<div className="healthy-state"><Activity size={20}/><span>{t('dashboard.inventoryHealthy')}</span></div>:<div className="alert-list">{data.lowStock.map((item)=><button key={item.id}onClick={()=>navigate('inventory',{recordId:item.id})}><AlertTriangle size={17}/><span><b>{item.name}</b><small>{item.currentStock} {item.unit} / {item.minimumStock} {t('ui.minimum')}</small></span></button>)}</div>}</Card>
    </section></>}</div>;
}
function Kpi({icon:Icon,label,value,tone}:{icon:React.ElementType;label:string;value:React.ReactNode;tone:string}){return<div className="kpi-card"><span className={`kpi-icon tone-${tone}`}><Icon size={20}/></span><div><span>{label}</span><strong>{value}</strong></div></div>}
function Quick({icon:Icon,label,onClick}:{icon:React.ElementType;label:string;onClick:()=>void}){return<button className="quick-action"onClick={onClick}><Icon size={19}/><span>{label}</span><ArrowRight size={14}/></button>}
