import{useCallback,useEffect,useState}from'react';
import{Plus,Receipt,RefreshCw,Search,WalletCards}from'lucide-react';
import{useTranslation}from'react-i18next';
import type{Expense}from'../../shared/types';
import{useApp}from'../context/AppContext';
import{Button,Card,DateText,EmptyState,FormField,IconButton,LoadingState,Modal,Money,PageHeader,Pagination}from'../components/UI';
function startMonth(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`}
export function Expenses(){const{t}=useTranslation();const{session,navOptions,run,notify,bootstrap}=useApp();const[items,setItems]=useState<Expense[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const[page,setPage]=useState(1);const[total,setTotal]=useState(0);const[pages,setPages]=useState(1);const[from,setFrom]=useState(startMonth());const[to,setTo]=useState(new Date().toISOString().slice(0,10));const[open,setOpen]=useState(false);
  const load=useCallback(async()=>{if(!session)return;setLoading(true);try{const data=await run(()=>window.dentiva.records.list(session.token,{entity:'expenses',page,pageSize:25,search,filters:{from,to}}));setItems(data.items as unknown as Expense[]);setTotal(data.total);setPages(data.totalPages);}catch{}finally{setLoading(false);}},[session,page,search,from,to,run]);useEffect(()=>{void load();},[load]);useEffect(()=>{if(navOptions.action==='new')setOpen(true);},[navOptions]);const sum=items.reduce((n,item)=>n+item.amountMinor,0);
  return<div className="page"><PageHeader title={t('expenses.title')}subtitle={t('expenses.subtitle')}actions={<Button icon={Plus}onClick={()=>setOpen(true)}>{t('expenses.new')}</Button>}/><section className="summary-strip"><div><WalletCards/><span><small>{t('expenses.title')}</small><strong><Money minor={sum}symbol={bootstrap?.clinic?.currencySymbol}/></strong></span></div><label>{t('common.date')}<input type="date"value={from}onChange={(e)=>setFrom(e.target.value)}/><span>—</span><input type="date"value={to}onChange={(e)=>setTo(e.target.value)}/></label></section><Card className="table-card"><div className="table-toolbar"><div className="search-box"><Search/><input value={search}onChange={(e)=>setSearch(e.target.value)}placeholder={t('common.search')}/></div><IconButton label={t('common.refresh')}icon={RefreshCw}onClick={load}/></div>{loading?<LoadingState/>:items.length===0?<EmptyState icon={Receipt}title={t('expenses.emptyTitle')}body={t('expenses.emptyBody')}action={<Button icon={Plus}onClick={()=>setOpen(true)}>{t('expenses.new')}</Button>}/>:<><div className="data-table-wrap"><table className="data-table"><thead><tr><th>{t('expenses.expense')}</th><th>{t('expenses.category')}</th><th>{t('expenses.expenseDate')}</th><th>{t('expenses.payee')}</th><th>{t('expenses.description')}</th><th>{t('expenses.method')}</th><th className="num">{t('common.amount')}</th></tr></thead><tbody>{items.map((item)=><tr key={item.id}><td className="code-cell">{item.expenseNumber}</td><td>{item.categoryName}</td><td><DateText value={item.expenseDate}/></td><td>{item.payee||'—'}</td><td>{item.description}</td><td>{item.method}</td><td className="num"><Money minor={item.amountMinor}symbol={bootstrap?.clinic?.currencySymbol}/></td></tr>)}</tbody></table></div><Pagination page={page}totalPages={pages}total={total}onChange={setPage}/></>}</Card><ExpenseForm open={open}onClose={()=>setOpen(false)}onSaved={()=>{setOpen(false);notify('success',t('common.success'));void load();}}/></div>;
}
function ExpenseForm({open,onClose,onSaved}:{open:boolean;onClose:()=>void;onSaved:()=>void}){const{t}=useTranslation();const{session,run}=useApp();const[categories,setCategories]=useState<Array<{id:string;name:string}>>([]);const[category,setCategory]=useState('');const[amount,setAmount]=useState(0);const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[payee,setPayee]=useState('');const[method,setMethod]=useState('Cash');const[reference,setReference]=useState('');const[description,setDescription]=useState('');const[busy,setBusy]=useState(false);useEffect(()=>{if(!open||!session)return;setAmount(0);setDate(new Date().toISOString().slice(0,10));setPayee('');setReference('');setDescription('');void window.dentiva.records.list(session.token,{entity:'expenses',page:1,pageSize:100,filters:{lookup:'categories'}}).then((r)=>{if(r.ok&&r.data){const list=r.data.items as unknown as Array<{id:string;name:string}>;setCategories(list);setCategory(list[0]?.id??'');}});},[open,session]);const save=async()=>{if(!session)return;setBusy(true);try{await run(()=>window.dentiva.records.create(session.token,'expenses',{categoryId:category,amountMinor:amount,expenseDate:date,payee:payee||null,method,reference:reference||null,description}));onSaved();}catch{}finally{setBusy(false);}};return<Modal open={open}onClose={onClose}title={t('expenses.new')}size="md"footer={<><Button variant="secondary"onClick={onClose}>{t('common.cancel')}</Button><Button onClick={save}disabled={busy||!category||amount<=0||description.trim().length<2}>{t('expenses.record')}</Button></>}><div className="form-grid cols-2"><FormField label={t('expenses.category')}required><select value={category}onChange={(e)=>setCategory(e.target.value)}>{categories.map((item)=><option key={item.id}value={item.id}>{item.name}</option>)}</select></FormField><FormField label={t('common.amount')}required><input type="number"min="0"step="0.01"value={(amount/100).toFixed(2)}onChange={(e)=>setAmount(Math.round(Number(e.target.value)*100))}/></FormField><FormField label={t('expenses.expenseDate')}required><input type="date"value={date}onChange={(e)=>setDate(e.target.value)}/></FormField><FormField label={t('expenses.payee')}><input value={payee}onChange={(e)=>setPayee(e.target.value)}/></FormField><FormField label={t('expenses.method')}><input value={method}onChange={(e)=>setMethod(e.target.value)}/></FormField><FormField label={t('expenses.reference')}><input value={reference}onChange={(e)=>setReference(e.target.value)}/></FormField><FormField label={t('expenses.description')}required className="span-2"><textarea rows={3}value={description}onChange={(e)=>setDescription(e.target.value)}/></FormField></div></Modal>}
