import{useState}from'react';
import{Eye,EyeOff,LoaderCircle,LockKeyhole,ShieldCheck}from'lucide-react';
import{useTranslation}from'react-i18next';
import{useApp}from'../context/AppContext';
import{Brand}from'../components/Brand';
import{Button,FormField}from'../components/UI';

export function Login(){const{t}=useTranslation();const{bootstrap,setSession,run,language,setLanguage}=useApp();const[username,setUsername]=useState('');const[password,setPassword]=useState('');const[show,setShow]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setError('');setBusy(true);try{const session=await run(()=>window.dentiva.auth.login({username,password}));setSession(session);}catch(err){setError(err instanceof Error?err.message:t('errors.session'));}finally{setBusy(false);}};
  return<div className="login-shell"><section className="login-brand"><div className="login-pattern"/><Brand inverse/><div className="login-message"><span className="setup-kicker">{t('ui.secureWorkspace')}</span><h1>{bootstrap?.clinic?.name}</h1><p>{t('appName')} — {t('tagline')}</p></div><div className="login-security"><ShieldCheck size={20}/><div><b>{t('ui.localDataProtection')}</b><span>{t('ui.securityFeatures')}</span></div></div></section><main className="login-main"><div className="login-language"><button className={language==='en'?'active':''}onClick={()=>setLanguage('en')}>EN</button><button className={language==='bn'?'active':''}onClick={()=>setLanguage('bn')}>বাংলা</button></div><form className="login-card"onSubmit={submit}><span className="login-lock"><LockKeyhole/></span><h2>{t('auth.welcome')}</h2><p>{t('auth.subtitle')}</p><FormField label={t('auth.username')}required><input value={username}onChange={(event)=>setUsername(event.target.value)}autoComplete="username"autoFocus/></FormField><FormField label={t('auth.password')}required><div className="password-input"><input type={show?'text':'password'}value={password}onChange={(event)=>setPassword(event.target.value)}autoComplete="current-password"/><button type="button"onClick={()=>setShow((value)=>!value)}aria-label={show?t('ui.hidePassword'):t('ui.showPassword')}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></FormField>{error&&<div className="inline-error">{error}</div>}<Button type="submit"size="lg"icon={busy?LoaderCircle:LockKeyhole}disabled={busy||!username||!password}>{busy?t('common.loading'):t('auth.signIn')}</Button><footer><span>Dentiva {bootstrap?.version}</span><span>{new Intl.DateTimeFormat(language==='bn'?'bn-BD':'en-BD',{dateStyle:'full'}).format(new Date())}</span></footer></form></main></div>;
}
