import{useCallback,useEffect,useState}from'react';
import{CalendarDays,FileDown,FileSpreadsheet,FileText,PackageSearch,Receipt,Stethoscope,UsersRound,WalletCards}from'lucide-react';
import{useTranslation}from'react-i18next';
import type{DateRange,ReportSummary}from'../../shared/types';
import{useApp}from'../context/AppContext';
import{Button,Card,LoadingState,Money,PageHeader}from'../components/UI';
function initial():DateRange{const to=new Date();const from=new Date(to);from.setMonth(from.getMonth()-1);return{from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10),preset:'1month'}}
const reportIcons={patients:UsersRound,appointments:CalendarDays,visits:Stethoscope,invoices:Receipt,payments:WalletCards,expenses:FileText,inventory:PackageSearch};
export function Reports(){const{t}=useTranslation();const{session,run,notify,bootstrap}=useApp();const[range,setRange]=useState(initial());const[data,setData]=useState<ReportSummary|null>(null);const[loading,setLoading]=useState(true);const[exporting,setExporting]=useState('');const load=useCallback(async()=>{if(!session)return;setLoading(true);try{setData(await run(()=>window.dentiva.reports.summary(session.token,range)));}catch{}finally{setLoading(false);}},[session,range,run]);useEffect(()=>{void load();},[load]);const reports=[['patients',t('reports.patientReport')],['appointments',t('reports.appointmentReport')],['visits',t('reports.clinicalReport')],['invoices',t('reports.invoiceReport')],['payments',t('reports.paymentReport')],['expenses',t('reports.expenseReport')],['inventory',t('reports.inventoryReport')]] as const;const exportReport=async(report:string,format:'csv'|'xlsx'|'pdf')=>{if(!session)return;setExporting(`${report}-${format}`);try{const result=await run(()=>window.dentiva.reports.export(session.token,{report,range,format}));notify('success',result.path);}catch{}finally{setExporting('');}};return<div className="page"><PageHeader title={t('reports.title')}subtitle={t('reports.subtitle')}actions={<div className="range-inputs"><input type="date"value={range.from}onChange={(e)=>setRange((r)=>({...r,from:e.target.value}))}/><span>—</span><input type="date"value={range.to}onChange={(e)=>setRange((r)=>({...r,to:e.target.value}))}/></div>}/>{loading?<LoadingState/>:<>{data&&<section className="report-summary"><div><UsersRound/><span><small>{t('reports.newPatients')}</small><b>{data.newPatients}</b></span></div><div><Stethoscope/><span><small>{t('reports.visits')}</small><b>{data.visits}</b></span></div><div><CalendarDays/><span><small>{t('reports.appointments')}</small><b>{data.appointments}</b></span></div><div><WalletCards/><span><small>{t('financials.income')}</small><b><Money minor={data.revenueMinor}symbol={bootstrap?.clinic?.currencySymbol}/></b></span></div></section>}<section className="report-grid">{reports.map(([key,label])=>{const Icon=reportIcons[key];return<Card key={key}className="report-card"><span className="report-icon"><Icon/></span><div><h3>{label}</h3><p>{range.from} — {range.to}</p></div><div className="report-actions"><Button size="sm"variant="quiet"icon={FileText}disabled={Boolean(exporting)}onClick={()=>void exportReport(key,'csv')}>CSV</Button><Button size="sm"variant="quiet"icon={FileSpreadsheet}disabled={Boolean(exporting)}onClick={()=>void exportReport(key,'xlsx')}>XLSX</Button><Button size="sm"variant="quiet"icon={FileDown}disabled={Boolean(exporting)}onClick={()=>void exportReport(key,'pdf')}>PDF</Button></div></Card>})}</section></>}</div>}
